'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IccService2Reference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IccService2Reference.IIccService2")>  _
    Public Interface IIccService2
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/InitialIccUploadDataQueryUI", ReplyAction:="http://tempuri.org/IIccService2/InitialIccUploadDataQueryUIResponse")>  _
        Function InitialIccUploadDataQueryUI(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryIccUploadData", ReplyAction:="http://tempuri.org/IIccService2/QueryIccUploadDataResponse")>  _
        Function QueryIccUploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryIccUploadDataDetail", ReplyAction:="http://tempuri.org/IIccService2/QueryIccUploadDataDetailResponse")>  _
        Function QueryIccUploadDataDetail(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/SaveIccUploadData", ReplyAction:="http://tempuri.org/IIccService2/SaveIccUploadDataResponse")>  _
        Function SaveIccUploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetOrganDonate", ReplyAction:="http://tempuri.org/IIccService2/queryGetOrganDonateResponse")>  _
        Function queryGetOrganDonate(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetOrganDonate", ReplyAction:="http://tempuri.org/IIccService2/updateGetOrganDonateResponse")>  _
        Function updateGetOrganDonate(ByVal Card_Sn As String, ByVal retOrganDonateMark As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetOrganDonate", ReplyAction:="http://tempuri.org/IIccService2/insertGetOrganDonateResponse")>  _
        Function insertGetOrganDonate(ByVal Card_Sn As String, ByVal retOrganDonateMark As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteTreatmentCode", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteTreatmentCodeResponse")>  _
        Function deleteWriteTreatmentCode(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteTreatmentFee", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteTreatmentFeeResponse")>  _
        Function deleteWriteTreatmentFee(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteHealthInsurance", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteHealthInsuranceResponse")>  _
        Function deleteWriteHealthInsurance(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteEmergentTel", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteEmergentTelResponse")>  _
        Function deleteWriteEmergentTel(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWritePredeliveryCheckup", ReplyAction:="http://tempuri.org/IIccService2/deleteWritePredeliveryCheckupResponse")>  _
        Function deleteWritePredeliveryCheckup(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteMultiPrescript", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteMultiPrescriptResponse")>  _
        Function deleteWriteMultiPrescript(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteAllergicMedicines", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteAllergicMedicinesResponse")>  _
        Function deleteWriteAllergicMedicines(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteInoculateData", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteInoculateDataResponse")>  _
        Function deleteWriteInoculateData(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteOrganDonate", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteOrganDonateResponse")>  _
        Function deleteWriteOrganDonate(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetEmergentTel", ReplyAction:="http://tempuri.org/IIccService2/queryGetEmergentTelResponse")>  _
        Function queryGetEmergentTel(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetEmergentTel", ReplyAction:="http://tempuri.org/IIccService2/updateGetEmergentTelResponse")>  _
        Function updateGetEmergentTel(ByVal Card_Sn As String, ByVal retEmergentTel As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetEmergentTel", ReplyAction:="http://tempuri.org/IIccService2/insertGetEmergentTelResponse")>  _
        Function insertGetEmergentTel(ByVal Card_Sn As String, ByVal retEmergentTel As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetCumulativeData", ReplyAction:="http://tempuri.org/IIccService2/queryGetCumulativeDataResponse")>  _
        Function queryGetCumulativeData(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetCumulativeData", ReplyAction:="http://tempuri.org/IIccService2/updateGetCumulativeDataResponse")>  _
        Function updateGetCumulativeData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetCumulativeData", ReplyAction:="http://tempuri.org/IIccService2/insertGetCumulativeDataResponse")>  _
        Function insertGetCumulativeData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetCumulativeFee", ReplyAction:="http://tempuri.org/IIccService2/queryGetCumulativeFeeResponse")>  _
        Function queryGetCumulativeFee(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetCumulativeFee", ReplyAction:="http://tempuri.org/IIccService2/updateGetCumulativeFeeResponse")>  _
        Function updateGetCumulativeFee(ByVal Card_Sn As String, ByVal retOutpatientFeeToatl As String, ByVal retHospitalFeeToatl As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetCumulativeFee", ReplyAction:="http://tempuri.org/IIccService2/insertGetCumulativeFeeResponse")>  _
        Function insertGetCumulativeFee(ByVal Card_Sn As String, ByVal retOutpatientFeeToatl As String, ByVal retHospitalFeeToatl As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetBasicData", ReplyAction:="http://tempuri.org/IIccService2/queryGetBasicDataResponse")>  _
        Function queryGetBasicData(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetBasicData", ReplyAction:="http://tempuri.org/IIccService2/updateGetBasicDataResponse")>  _
        Function updateGetBasicData(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetBasicData2", ReplyAction:="http://tempuri.org/IIccService2/updateGetBasicData2Response")>  _
        Function updateGetBasicData2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetBasicData", ReplyAction:="http://tempuri.org/IIccService2/insertGetBasicDataResponse")>  _
        Function insertGetBasicData(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteGetBasicData", ReplyAction:="http://tempuri.org/IIccService2/deleteGetBasicDataResponse")>  _
        Function deleteGetBasicData(ByVal Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetBasicData2", ReplyAction:="http://tempuri.org/IIccService2/insertGetBasicData2Response")>  _
        Function insertGetBasicData2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryReadPrescription", ReplyAction:="http://tempuri.org/IIccService2/queryReadPrescriptionResponse")>  _
        Function queryReadPrescription(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateReadPrescription", ReplyAction:="http://tempuri.org/IIccService2/updateReadPrescriptionResponse")>  _
        Function updateReadPrescription(ByVal Card_Sn As String, ByVal retMainValueList As System.Data.DataSet, ByVal retLongTermValueList As System.Data.DataSet, ByVal retHVEValueList As System.Data.DataSet, ByVal retAllergicValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteReadPrescription", ReplyAction:="http://tempuri.org/IIccService2/deleteReadPrescriptionResponse")>  _
        Function deleteReadPrescription(ByVal Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertReadPrescription", ReplyAction:="http://tempuri.org/IIccService2/insertReadPrescriptionResponse")>  _
        Function insertReadPrescription(ByVal Card_Sn As String, ByVal retMainValueList As System.Data.DataSet, ByVal retLongTermValueList As System.Data.DataSet, ByVal retHVEValueList As System.Data.DataSet, ByVal retAllergicValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWritePrescription", ReplyAction:="http://tempuri.org/IIccService2/deleteWritePrescriptionResponse")>  _
        Function deleteWritePrescription(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/queryGetRegisterBasic2", ReplyAction:="http://tempuri.org/IIccService2/queryGetRegisterBasic2Response")>  _
        Function queryGetRegisterBasic2(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/updateGetRegisterBasic2", ReplyAction:="http://tempuri.org/IIccService2/updateGetRegisterBasic2Response")>  _
        Function updateGetRegisterBasic2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/insertGetRegisterBasic2", ReplyAction:="http://tempuri.org/IIccService2/insertGetRegisterBasic2Response")>  _
        Function insertGetRegisterBasic2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/deleteWriteTreatmentData", ReplyAction:="http://tempuri.org/IIccService2/deleteWriteTreatmentDataResponse")>  _
        Function deleteWriteTreatmentData(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/UpdateICCOrderUploadForPrescriptionSignA79", ReplyAction:="http://tempuri.org/IIccService2/UpdateICCOrderUploadForPrescriptionSignA79Respons"& _ 
            "e")>  _
        Function UpdateICCOrderUploadForPrescriptionSignA79(ByVal ds As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/UpdateICCBacterinUploadForPrescriptionSignA79", ReplyAction:="http://tempuri.org/IIccService2/UpdateICCBacterinUploadForPrescriptionSignA79Resp"& _ 
            "onse")>  _
        Function UpdateICCBacterinUploadForPrescriptionSignA79(ByVal ds As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/getConfigDataForICCUpload", ReplyAction:="http://tempuri.org/IIccService2/getConfigDataForICCUploadResponse")>  _
        Function getConfigDataForICCUpload() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/ImportFeedbackData", ReplyAction:="http://tempuri.org/IIccService2/ImportFeedbackDataResponse")>  _
        Function ImportFeedbackData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryMaxCountOfDay", ReplyAction:="http://tempuri.org/IIccService2/QueryMaxCountOfDayResponse")>  _
        Function QueryMaxCountOfDay(ByVal Import_Date As Date) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryFeedBackData", ReplyAction:="http://tempuri.org/IIccService2/QueryFeedBackDataResponse")>  _
        Function QueryFeedBackData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/ImportFeedbackDuporderData", ReplyAction:="http://tempuri.org/IIccService2/ImportFeedbackDuporderDataResponse")>  _
        Function ImportFeedbackDuporderData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryFeedBackDuporderData", ReplyAction:="http://tempuri.org/IIccService2/QueryFeedBackDuporderDataResponse")>  _
        Function QueryFeedBackDuporderData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/Query24HourUploadedRate", ReplyAction:="http://tempuri.org/IIccService2/Query24HourUploadedRateResponse")>  _
        Function Query24HourUploadedRate(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/Query24UnuploadData", ReplyAction:="http://tempuri.org/IIccService2/Query24UnuploadDataResponse")>  _
        Function Query24UnuploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService2/QueryIccConnectionHistory", ReplyAction:="http://tempuri.org/IIccService2/QueryIccConnectionHistoryResponse")>  _
        Function QueryIccConnectionHistory(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IIccService2Channel
        Inherits IccService2Reference.IIccService2, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IccService2Client
        Inherits System.ServiceModel.ClientBase(Of IccService2Reference.IIccService2)
        Implements IccService2Reference.IIccService2
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function InitialIccUploadDataQueryUI(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.InitialIccUploadDataQueryUI
            Return MyBase.Channel.InitialIccUploadDataQueryUI(Param)
        End Function
        
        Public Function QueryIccUploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.QueryIccUploadData
            Return MyBase.Channel.QueryIccUploadData(Param)
        End Function
        
        Public Function QueryIccUploadDataDetail(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.QueryIccUploadDataDetail
            Return MyBase.Channel.QueryIccUploadDataDetail(Param)
        End Function
        
        Public Function SaveIccUploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As System.Data.DataSet Implements IccService2Reference.IIccService2.SaveIccUploadData
            Return MyBase.Channel.SaveIccUploadData(Param, InputDs)
        End Function
        
        Public Function queryGetOrganDonate(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetOrganDonate
            Return MyBase.Channel.queryGetOrganDonate(Card_Sn)
        End Function
        
        Public Function updateGetOrganDonate(ByVal Card_Sn As String, ByVal retOrganDonateMark As String) As Integer Implements IccService2Reference.IIccService2.updateGetOrganDonate
            Return MyBase.Channel.updateGetOrganDonate(Card_Sn, retOrganDonateMark)
        End Function
        
        Public Function insertGetOrganDonate(ByVal Card_Sn As String, ByVal retOrganDonateMark As String) As Integer Implements IccService2Reference.IIccService2.insertGetOrganDonate
            Return MyBase.Channel.insertGetOrganDonate(Card_Sn, retOrganDonateMark)
        End Function
        
        Public Function deleteWriteTreatmentCode(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteTreatmentCode
            Return MyBase.Channel.deleteWriteTreatmentCode(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteTreatmentFee(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteTreatmentFee
            Return MyBase.Channel.deleteWriteTreatmentFee(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteHealthInsurance(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteHealthInsurance
            Return MyBase.Channel.deleteWriteHealthInsurance(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteEmergentTel(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteEmergentTel
            Return MyBase.Channel.deleteWriteEmergentTel(pk_Card_Sn)
        End Function
        
        Public Function deleteWritePredeliveryCheckup(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWritePredeliveryCheckup
            Return MyBase.Channel.deleteWritePredeliveryCheckup(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteMultiPrescript(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteMultiPrescript
            Return MyBase.Channel.deleteWriteMultiPrescript(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteAllergicMedicines(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteAllergicMedicines
            Return MyBase.Channel.deleteWriteAllergicMedicines(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteInoculateData(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteInoculateData
            Return MyBase.Channel.deleteWriteInoculateData(pk_Card_Sn)
        End Function
        
        Public Function deleteWriteOrganDonate(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteOrganDonate
            Return MyBase.Channel.deleteWriteOrganDonate(pk_Card_Sn)
        End Function
        
        Public Function queryGetEmergentTel(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetEmergentTel
            Return MyBase.Channel.queryGetEmergentTel(Card_Sn)
        End Function
        
        Public Function updateGetEmergentTel(ByVal Card_Sn As String, ByVal retEmergentTel As String) As Integer Implements IccService2Reference.IIccService2.updateGetEmergentTel
            Return MyBase.Channel.updateGetEmergentTel(Card_Sn, retEmergentTel)
        End Function
        
        Public Function insertGetEmergentTel(ByVal Card_Sn As String, ByVal retEmergentTel As String) As Integer Implements IccService2Reference.IIccService2.insertGetEmergentTel
            Return MyBase.Channel.insertGetEmergentTel(Card_Sn, retEmergentTel)
        End Function
        
        Public Function queryGetCumulativeData(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetCumulativeData
            Return MyBase.Channel.queryGetCumulativeData(Card_Sn)
        End Function
        
        Public Function updateGetCumulativeData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.updateGetCumulativeData
            Return MyBase.Channel.updateGetCumulativeData(Card_Sn, retValueList)
        End Function
        
        Public Function insertGetCumulativeData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.insertGetCumulativeData
            Return MyBase.Channel.insertGetCumulativeData(Card_Sn, retValueList)
        End Function
        
        Public Function queryGetCumulativeFee(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetCumulativeFee
            Return MyBase.Channel.queryGetCumulativeFee(Card_Sn)
        End Function
        
        Public Function updateGetCumulativeFee(ByVal Card_Sn As String, ByVal retOutpatientFeeToatl As String, ByVal retHospitalFeeToatl As String) As Integer Implements IccService2Reference.IIccService2.updateGetCumulativeFee
            Return MyBase.Channel.updateGetCumulativeFee(Card_Sn, retOutpatientFeeToatl, retHospitalFeeToatl)
        End Function
        
        Public Function insertGetCumulativeFee(ByVal Card_Sn As String, ByVal retOutpatientFeeToatl As String, ByVal retHospitalFeeToatl As String) As Integer Implements IccService2Reference.IIccService2.insertGetCumulativeFee
            Return MyBase.Channel.insertGetCumulativeFee(Card_Sn, retOutpatientFeeToatl, retHospitalFeeToatl)
        End Function
        
        Public Function queryGetBasicData(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetBasicData
            Return MyBase.Channel.queryGetBasicData(Card_Sn)
        End Function
        
        Public Function updateGetBasicData(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.updateGetBasicData
            Return MyBase.Channel.updateGetBasicData(Card_Sn, retValue)
        End Function
        
        Public Function updateGetBasicData2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.updateGetBasicData2
            Return MyBase.Channel.updateGetBasicData2(Card_Sn, retValue)
        End Function
        
        Public Function insertGetBasicData(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.insertGetBasicData
            Return MyBase.Channel.insertGetBasicData(Card_Sn, retValue)
        End Function
        
        Public Function deleteGetBasicData(ByVal Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteGetBasicData
            Return MyBase.Channel.deleteGetBasicData(Card_Sn)
        End Function
        
        Public Function insertGetBasicData2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.insertGetBasicData2
            Return MyBase.Channel.insertGetBasicData2(Card_Sn, retValue)
        End Function
        
        Public Function queryReadPrescription(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryReadPrescription
            Return MyBase.Channel.queryReadPrescription(Card_Sn)
        End Function
        
        Public Function updateReadPrescription(ByVal Card_Sn As String, ByVal retMainValueList As System.Data.DataSet, ByVal retLongTermValueList As System.Data.DataSet, ByVal retHVEValueList As System.Data.DataSet, ByVal retAllergicValueList As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.updateReadPrescription
            Return MyBase.Channel.updateReadPrescription(Card_Sn, retMainValueList, retLongTermValueList, retHVEValueList, retAllergicValueList)
        End Function
        
        Public Function deleteReadPrescription(ByVal Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteReadPrescription
            Return MyBase.Channel.deleteReadPrescription(Card_Sn)
        End Function
        
        Public Function insertReadPrescription(ByVal Card_Sn As String, ByVal retMainValueList As System.Data.DataSet, ByVal retLongTermValueList As System.Data.DataSet, ByVal retHVEValueList As System.Data.DataSet, ByVal retAllergicValueList As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.insertReadPrescription
            Return MyBase.Channel.insertReadPrescription(Card_Sn, retMainValueList, retLongTermValueList, retHVEValueList, retAllergicValueList)
        End Function
        
        Public Function deleteWritePrescription(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWritePrescription
            Return MyBase.Channel.deleteWritePrescription(pk_Card_Sn)
        End Function
        
        Public Function queryGetRegisterBasic2(ByVal Card_Sn As String) As System.Data.DataSet Implements IccService2Reference.IIccService2.queryGetRegisterBasic2
            Return MyBase.Channel.queryGetRegisterBasic2(Card_Sn)
        End Function
        
        Public Function updateGetRegisterBasic2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.updateGetRegisterBasic2
            Return MyBase.Channel.updateGetRegisterBasic2(Card_Sn, retValue)
        End Function
        
        Public Function insertGetRegisterBasic2(ByVal Card_Sn As String, ByVal retValue As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.insertGetRegisterBasic2
            Return MyBase.Channel.insertGetRegisterBasic2(Card_Sn, retValue)
        End Function
        
        Public Function deleteWriteTreatmentData(ByVal pk_Card_Sn As String) As Integer Implements IccService2Reference.IIccService2.deleteWriteTreatmentData
            Return MyBase.Channel.deleteWriteTreatmentData(pk_Card_Sn)
        End Function
        
        Public Function UpdateICCOrderUploadForPrescriptionSignA79(ByVal ds As System.Data.DataSet) As String Implements IccService2Reference.IIccService2.UpdateICCOrderUploadForPrescriptionSignA79
            Return MyBase.Channel.UpdateICCOrderUploadForPrescriptionSignA79(ds)
        End Function
        
        Public Function UpdateICCBacterinUploadForPrescriptionSignA79(ByVal ds As System.Data.DataSet) As String Implements IccService2Reference.IIccService2.UpdateICCBacterinUploadForPrescriptionSignA79
            Return MyBase.Channel.UpdateICCBacterinUploadForPrescriptionSignA79(ds)
        End Function
        
        Public Function getConfigDataForICCUpload() As System.Data.DataTable Implements IccService2Reference.IIccService2.getConfigDataForICCUpload
            Return MyBase.Channel.getConfigDataForICCUpload
        End Function
        
        Public Function ImportFeedbackData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.ImportFeedbackData
            Return MyBase.Channel.ImportFeedbackData(Param, InputDs)
        End Function
        
        Public Function QueryMaxCountOfDay(ByVal Import_Date As Date) As Integer Implements IccService2Reference.IIccService2.QueryMaxCountOfDay
            Return MyBase.Channel.QueryMaxCountOfDay(Import_Date)
        End Function
        
        Public Function QueryFeedBackData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.QueryFeedBackData
            Return MyBase.Channel.QueryFeedBackData(Param)
        End Function
        
        Public Function ImportFeedbackDuporderData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object), ByVal InputDs As System.Data.DataSet) As Integer Implements IccService2Reference.IIccService2.ImportFeedbackDuporderData
            Return MyBase.Channel.ImportFeedbackDuporderData(Param, InputDs)
        End Function
        
        Public Function QueryFeedBackDuporderData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.QueryFeedBackDuporderData
            Return MyBase.Channel.QueryFeedBackDuporderData(Param)
        End Function
        
        Public Function Query24HourUploadedRate(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.Query24HourUploadedRate
            Return MyBase.Channel.Query24HourUploadedRate(Param)
        End Function
        
        Public Function Query24UnuploadData(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.Query24UnuploadData
            Return MyBase.Channel.Query24UnuploadData(Param)
        End Function
        
        Public Function QueryIccConnectionHistory(ByVal Param As System.Collections.Generic.Dictionary(Of String, Object)) As System.Data.DataSet Implements IccService2Reference.IIccService2.QueryIccConnectionHistory
            Return MyBase.Channel.QueryIccConnectionHistory(Param)
        End Function
    End Class
End Namespace
