'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.34209
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace RptServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RptServiceReference.IRptService")>  _
    Public Interface IRptService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRptService/getPrinterName", ReplyAction:="http://tempuri.org/IRptService/getPrinterNameResponse")>  _
        Function getPrinterName(ByVal id As String, ByVal type As Integer, ByVal con As Object) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRptService/getReportID", ReplyAction:="http://tempuri.org/IRptService/getReportIDResponse")>  _
        Function getReportID() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRptServiceChannel
        Inherits RptServiceReference.IRptService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RptServiceClient
        Inherits System.ServiceModel.ClientBase(Of RptServiceReference.IRptService)
        Implements RptServiceReference.IRptService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getPrinterName(ByVal id As String, ByVal type As Integer, ByVal con As Object) As String Implements RptServiceReference.IRptService.getPrinterName
            Return MyBase.Channel.getPrinterName(id, type, con)
        End Function
        
        Public Function getReportID() As String Implements RptServiceReference.IRptService.getReportID
            Return MyBase.Channel.getReportID
        End Function
    End Class
End Namespace
