'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.34209
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ArmServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ArmServiceReference.IArmService")>  _
    Public Interface IArmService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/Login", ReplyAction:="http://tempuri.org/IArmService/LoginResponse")>  _
        Function Login(ByVal id As String, ByVal password As String, ByVal system_type_id As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/LoginForSys", ReplyAction:="http://tempuri.org/IArmService/LoginForSysResponse")>  _
        Function LoginForSys(ByVal role As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/LoginForAgent", ReplyAction:="http://tempuri.org/IArmService/LoginForAgentResponse")>  _
        Function LoginForAgent(ByVal loginUserId As String, ByVal userRoleArrayList() As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryForRoleRightsMaintain", ReplyAction:="http://tempuri.org/IArmService/queryForRoleRightsMaintainResponse")>  _
        Function queryForRoleRightsMaintain(ByVal RoleID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ConfirmRoleRights", ReplyAction:="http://tempuri.org/IArmService/ConfirmRoleRightsResponse")>  _
        Sub ConfirmRoleRights(ByVal DtValue As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ArmForUser", ReplyAction:="http://tempuri.org/IArmService/ArmForUserResponse")>  _
        Function ArmForUser(ByVal id As String, ByVal password As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AddUser", ReplyAction:="http://tempuri.org/IArmService/AddUserResponse")>  _
        Sub AddUser(ByVal ds As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ModifyUser", ReplyAction:="http://tempuri.org/IArmService/ModifyUserResponse")>  _
        Sub ModifyUser(ByVal ds As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/DeleteUser", ReplyAction:="http://tempuri.org/IArmService/DeleteUserResponse")>  _
        Sub DeleteUser(ByVal ds As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/QueryUser", ReplyAction:="http://tempuri.org/IArmService/QueryUserResponse")>  _
        Function QueryUser(ByVal ds As System.Data.DataSet) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ChangePassword", ReplyAction:="http://tempuri.org/IArmService/ChangePasswordResponse")>  _
        Function ChangePassword(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ResetPassword", ReplyAction:="http://tempuri.org/IArmService/ResetPasswordResponse")>  _
        Function ResetPassword(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/LoginModuleLoginBySectionCode", ReplyAction:="http://tempuri.org/IArmService/LoginModuleLoginBySectionCodeResponse")>  _
        Function LoginModuleLoginBySectionCode(ByVal id As String, ByVal password As String, ByVal SectionCode As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AddRole", ReplyAction:="http://tempuri.org/IArmService/AddRoleResponse")>  _
        Function AddRole(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ModifyRole", ReplyAction:="http://tempuri.org/IArmService/ModifyRoleResponse")>  _
        Function ModifyRole(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/DeleteRole", ReplyAction:="http://tempuri.org/IArmService/DeleteRoleResponse")>  _
        Function DeleteRole(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/QueryRole", ReplyAction:="http://tempuri.org/IArmService/QueryRoleResponse")>  _
        Function QueryRole(ByVal roleID As String, ByVal roleName As String, ByVal isValid As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/RoleBelongQuery", ReplyAction:="http://tempuri.org/IArmService/RoleBelongQueryResponse")>  _
        Function RoleBelongQuery(ByVal ds As System.Data.DataSet) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/RoleBelongUpdate", ReplyAction:="http://tempuri.org/IArmService/RoleBelongUpdateResponse")>  _
        Function RoleBelongUpdate(ByVal dsParam As System.Data.DataSet, ByVal dsRoleInfo As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppGetAppSystem", ReplyAction:="http://tempuri.org/IArmService/AppGetAppSystemResponse")>  _
        Function AppGetAppSystem(ByVal app_system_no As String, ByVal app_system_name As String, ByVal app_display_order As String, ByVal app_flag_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppQueryByPK", ReplyAction:="http://tempuri.org/IArmService/AppQueryByPKResponse")>  _
        Function AppQueryByPK(ByRef pk_app_system_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppInsert", ReplyAction:="http://tempuri.org/IArmService/AppInsertResponse")>  _
        Function AppInsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppDelete", ReplyAction:="http://tempuri.org/IArmService/AppDeleteResponse")>  _
        Function AppDelete(ByRef pk_app_system_no As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppUpdate", ReplyAction:="http://tempuri.org/IArmService/AppUpdateResponse")>  _
        Function AppUpdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/AppGetAppSystemCombobox", ReplyAction:="http://tempuri.org/IArmService/AppGetAppSystemComboboxResponse")>  _
        Function AppGetAppSystemCombobox() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubGetSubSystem", ReplyAction:="http://tempuri.org/IArmService/SubGetSubSystemResponse")>  _
        Function SubGetSubSystem(ByVal sub_system_no As String, ByVal sub_system_name As String, ByVal sub_app_system_no As String, ByVal sub_display_order As String, ByVal sub_flag_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubQueryByPK", ReplyAction:="http://tempuri.org/IArmService/SubQueryByPKResponse")>  _
        Function SubQueryByPK(ByRef pk_sub_system_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubInsert", ReplyAction:="http://tempuri.org/IArmService/SubInsertResponse")>  _
        Function SubInsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubDelete", ReplyAction:="http://tempuri.org/IArmService/SubDeleteResponse")>  _
        Function SubDelete(ByRef pk_sub_system_no As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubUpdate", ReplyAction:="http://tempuri.org/IArmService/SubUpdateResponse")>  _
        Function SubUpdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/SubGetSubSystemCombobox", ReplyAction:="http://tempuri.org/IArmService/SubGetSubSystemComboboxResponse")>  _
        Function SubGetSubSystemCombobox(ByVal sub_app_system_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskGetAllSystem", ReplyAction:="http://tempuri.org/IArmService/TskGetAllSystemResponse")>  _
        Function TskGetAllSystem(ByVal app_system_no As String, ByVal tsk_sub_system_no As String, ByVal tsk_task_no As String, ByVal tsk_task_name As String, ByVal tsk_display_order As String, ByVal tsk_task_flag_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskQueryByPK", ReplyAction:="http://tempuri.org/IArmService/TskQueryByPKResponse")>  _
        Function TskQueryByPK(ByRef pk_tsk_task_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskInsert", ReplyAction:="http://tempuri.org/IArmService/TskInsertResponse")>  _
        Function TskInsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskDelete", ReplyAction:="http://tempuri.org/IArmService/TskDeleteResponse")>  _
        Function TskDelete(ByRef pk_tsk_task_no As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskUpdate", ReplyAction:="http://tempuri.org/IArmService/TskUpdateResponse")>  _
        Function TskUpdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/TskGetTskSystemCombobox", ReplyAction:="http://tempuri.org/IArmService/TskGetTskSystemComboboxResponse")>  _
        Function TskGetTskSystemCombobox(ByVal tsk_sub_system_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunGetAllSystem", ReplyAction:="http://tempuri.org/IArmService/FunGetAllSystemResponse")>  _
        Function FunGetAllSystem(ByVal app_system_no As String, ByVal sub_system_no As String, ByVal fun_task_no As String, ByVal fun_function_no As String, ByVal fun_function_name As String, ByVal fun_content As String, ByVal fun_special_flag As String, ByVal fun_display_order As String, ByVal fun_flag_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunQueryByPK", ReplyAction:="http://tempuri.org/IArmService/FunQueryByPKResponse")>  _
        Function FunQueryByPK(ByRef pk_fun_function_no As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunQueryByLogin", ReplyAction:="http://tempuri.org/IArmService/FunQueryByLoginResponse")>  _
        Function FunQueryByLogin() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunInsert", ReplyAction:="http://tempuri.org/IArmService/FunInsertResponse")>  _
        Function FunInsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunDelete", ReplyAction:="http://tempuri.org/IArmService/FunDeleteResponse")>  _
        Function FunDelete(ByRef pk_fun_function_no As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/FunUpdate", ReplyAction:="http://tempuri.org/IArmService/FunUpdateResponse")>  _
        Function FunUpdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/insertLogonDate", ReplyAction:="http://tempuri.org/IArmService/insertLogonDateResponse")>  _
        Function insertLogonDate(ByVal ip As String, ByVal employeeCode As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/updateLogoutDate", ReplyAction:="http://tempuri.org/IArmService/updateLogoutDateResponse")>  _
        Function updateLogoutDate(ByVal ip As String, ByVal employeeCode As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryIP", ReplyAction:="http://tempuri.org/IArmService/queryIPResponse")>  _
        Function queryIP() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/insertLogonDateBySystem", ReplyAction:="http://tempuri.org/IArmService/insertLogonDateBySystemResponse")>  _
        Function insertLogonDateBySystem(ByVal systemNo As String, ByVal loginDate As String, ByVal ip As String, ByVal employeeCode As String, ByVal agentCode As String, ByVal machineName As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/updateLogoutDateBySystem", ReplyAction:="http://tempuri.org/IArmService/updateLogoutDateBySystemResponse")>  _
        Function updateLogoutDateBySystem(ByVal systemNo As String, ByVal loginDate As String, ByVal ip As String, ByVal employeeCode As String, ByVal agentCode As String, ByVal machineName As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryIPBySystem", ReplyAction:="http://tempuri.org/IArmService/queryIPBySystemResponse")>  _
        Function queryIPBySystem(ByVal systemNo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryEmployeeRoleData", ReplyAction:="http://tempuri.org/IArmService/queryEmployeeRoleDataResponse")>  _
        Function queryEmployeeRoleData(ByVal role As String, ByVal employeeCode As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/getPassword", ReplyAction:="http://tempuri.org/IArmService/getPasswordResponse")>  _
        Function getPassword(ByVal user As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/saveLogonFailure", ReplyAction:="http://tempuri.org/IArmService/saveLogonFailureResponse")>  _
        Function saveLogonFailure(ByVal employeeCode As String, ByVal ip As String, ByVal machineName As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/insertProfile", ReplyAction:="http://tempuri.org/IArmService/insertProfileResponse")>  _
        Function insertProfile(ByVal ds As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/deleteProfile", ReplyAction:="http://tempuri.org/IArmService/deleteProfileResponse")>  _
        Function deleteProfile(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File_Name As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryProfileByPk", ReplyAction:="http://tempuri.org/IArmService/queryProfileByPkResponse")>  _
        Function queryProfileByPk(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File_Name As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryProfile", ReplyAction:="http://tempuri.org/IArmService/queryProfileResponse")>  _
        Function queryProfile(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal flag As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/updateProfileDefault", ReplyAction:="http://tempuri.org/IArmService/updateProfileDefaultResponse")>  _
        Function updateProfileDefault(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File As String, ByVal flag As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/RoleQueryByEmployee", ReplyAction:="http://tempuri.org/IArmService/RoleQueryByEmployeeResponse")>  _
        Function RoleQueryByEmployee(ByVal Employee_Code As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/EmployeeQueryByRole", ReplyAction:="http://tempuri.org/IArmService/EmployeeQueryByRoleResponse")>  _
        Function EmployeeQueryByRole(ByVal Role_Id As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/EmployeeQueryByFunction", ReplyAction:="http://tempuri.org/IArmService/EmployeeQueryByFunctionResponse")>  _
        Function EmployeeQueryByFunction(ByVal Fun_Function_No As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/insertFunRecord", ReplyAction:="http://tempuri.org/IArmService/insertFunRecordResponse")>  _
        Function insertFunRecord(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/insertArmAgentAuth", ReplyAction:="http://tempuri.org/IArmService/insertArmAgentAuthResponse")>  _
        Function insertArmAgentAuth(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/deleteArmAgentAuth", ReplyAction:="http://tempuri.org/IArmService/deleteArmAgentAuthResponse")>  _
        Function deleteArmAgentAuth(ByVal employeeCode As String, ByVal agentCode As String, ByVal roleId As String, ByVal effectDate As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryByAgentEmployeeCode", ReplyAction:="http://tempuri.org/IArmService/queryByAgentEmployeeCodeResponse")>  _
        Function queryByAgentEmployeeCode(ByRef pk_employee_code As String, ByRef pk_agent_code As String, ByVal role_id As String, ByVal effect_date As String, ByVal end_date As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryArmRecord", ReplyAction:="http://tempuri.org/IArmService/queryArmRecordResponse")>  _
        Function queryArmRecord(ByVal employeeCode As String, ByVal functionNo As String, ByVal startDate As String, ByVal endDate As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/queryRoleRightsByMemberOf", ReplyAction:="http://tempuri.org/IArmService/queryRoleRightsByMemberOfResponse")>  _
        Function queryRoleRightsByMemberOf(ByVal userMemberOf As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IArmService/ArmLogonFailureQueryLoginFailure", ReplyAction:="http://tempuri.org/IArmService/ArmLogonFailureQueryLoginFailureResponse")>  _
        Function ArmLogonFailureQueryLoginFailure(ByVal str_StartDay As String, ByVal str_EndDay As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IArmServiceChannel
        Inherits ArmServiceReference.IArmService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ArmServiceClient
        Inherits System.ServiceModel.ClientBase(Of ArmServiceReference.IArmService)
        Implements ArmServiceReference.IArmService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal id As String, ByVal password As String, ByVal system_type_id As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.Login
            Return MyBase.Channel.Login(id, password, system_type_id)
        End Function
        
        Public Function LoginForSys(ByVal role As String) As System.Data.DataTable Implements ArmServiceReference.IArmService.LoginForSys
            Return MyBase.Channel.LoginForSys(role)
        End Function
        
        Public Function LoginForAgent(ByVal loginUserId As String, ByVal userRoleArrayList() As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.LoginForAgent
            Return MyBase.Channel.LoginForAgent(loginUserId, userRoleArrayList)
        End Function
        
        Public Function queryForRoleRightsMaintain(ByVal RoleID As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryForRoleRightsMaintain
            Return MyBase.Channel.queryForRoleRightsMaintain(RoleID)
        End Function
        
        Public Sub ConfirmRoleRights(ByVal DtValue As System.Data.DataSet) Implements ArmServiceReference.IArmService.ConfirmRoleRights
            MyBase.Channel.ConfirmRoleRights(DtValue)
        End Sub
        
        Public Function ArmForUser(ByVal id As String, ByVal password As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.ArmForUser
            Return MyBase.Channel.ArmForUser(id, password)
        End Function
        
        Public Sub AddUser(ByVal ds As System.Data.DataSet) Implements ArmServiceReference.IArmService.AddUser
            MyBase.Channel.AddUser(ds)
        End Sub
        
        Public Sub ModifyUser(ByVal ds As System.Data.DataSet) Implements ArmServiceReference.IArmService.ModifyUser
            MyBase.Channel.ModifyUser(ds)
        End Sub
        
        Public Sub DeleteUser(ByVal ds As System.Data.DataSet) Implements ArmServiceReference.IArmService.DeleteUser
            MyBase.Channel.DeleteUser(ds)
        End Sub
        
        Public Function QueryUser(ByVal ds As System.Data.DataSet) As System.Data.DataSet Implements ArmServiceReference.IArmService.QueryUser
            Return MyBase.Channel.QueryUser(ds)
        End Function
        
        Public Function ChangePassword(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.ChangePassword
            Return MyBase.Channel.ChangePassword(ds)
        End Function
        
        Public Function ResetPassword(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.ResetPassword
            Return MyBase.Channel.ResetPassword(ds)
        End Function
        
        Public Function LoginModuleLoginBySectionCode(ByVal id As String, ByVal password As String, ByVal SectionCode As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.LoginModuleLoginBySectionCode
            Return MyBase.Channel.LoginModuleLoginBySectionCode(id, password, SectionCode)
        End Function
        
        Public Function AddRole(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.AddRole
            Return MyBase.Channel.AddRole(ds)
        End Function
        
        Public Function ModifyRole(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.ModifyRole
            Return MyBase.Channel.ModifyRole(ds)
        End Function
        
        Public Function DeleteRole(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.DeleteRole
            Return MyBase.Channel.DeleteRole(ds)
        End Function
        
        Public Function QueryRole(ByVal roleID As String, ByVal roleName As String, ByVal isValid As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.QueryRole
            Return MyBase.Channel.QueryRole(roleID, roleName, isValid)
        End Function
        
        Public Function RoleBelongQuery(ByVal ds As System.Data.DataSet) As System.Data.DataSet Implements ArmServiceReference.IArmService.RoleBelongQuery
            Return MyBase.Channel.RoleBelongQuery(ds)
        End Function
        
        Public Function RoleBelongUpdate(ByVal dsParam As System.Data.DataSet, ByVal dsRoleInfo As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.RoleBelongUpdate
            Return MyBase.Channel.RoleBelongUpdate(dsParam, dsRoleInfo)
        End Function
        
        Public Function AppGetAppSystem(ByVal app_system_no As String, ByVal app_system_name As String, ByVal app_display_order As String, ByVal app_flag_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.AppGetAppSystem
            Return MyBase.Channel.AppGetAppSystem(app_system_no, app_system_name, app_display_order, app_flag_no)
        End Function
        
        Public Function AppQueryByPK(ByRef pk_app_system_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.AppQueryByPK
            Return MyBase.Channel.AppQueryByPK(pk_app_system_no)
        End Function
        
        Public Function AppInsert(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.AppInsert
            Return MyBase.Channel.AppInsert(ds)
        End Function
        
        Public Function AppDelete(ByRef pk_app_system_no As String) As Integer Implements ArmServiceReference.IArmService.AppDelete
            Return MyBase.Channel.AppDelete(pk_app_system_no)
        End Function
        
        Public Function AppUpdate(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.AppUpdate
            Return MyBase.Channel.AppUpdate(ds)
        End Function
        
        Public Function AppGetAppSystemCombobox() As System.Data.DataSet Implements ArmServiceReference.IArmService.AppGetAppSystemCombobox
            Return MyBase.Channel.AppGetAppSystemCombobox
        End Function
        
        Public Function SubGetSubSystem(ByVal sub_system_no As String, ByVal sub_system_name As String, ByVal sub_app_system_no As String, ByVal sub_display_order As String, ByVal sub_flag_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.SubGetSubSystem
            Return MyBase.Channel.SubGetSubSystem(sub_system_no, sub_system_name, sub_app_system_no, sub_display_order, sub_flag_no)
        End Function
        
        Public Function SubQueryByPK(ByRef pk_sub_system_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.SubQueryByPK
            Return MyBase.Channel.SubQueryByPK(pk_sub_system_no)
        End Function
        
        Public Function SubInsert(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.SubInsert
            Return MyBase.Channel.SubInsert(ds)
        End Function
        
        Public Function SubDelete(ByRef pk_sub_system_no As String) As Integer Implements ArmServiceReference.IArmService.SubDelete
            Return MyBase.Channel.SubDelete(pk_sub_system_no)
        End Function
        
        Public Function SubUpdate(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.SubUpdate
            Return MyBase.Channel.SubUpdate(ds)
        End Function
        
        Public Function SubGetSubSystemCombobox(ByVal sub_app_system_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.SubGetSubSystemCombobox
            Return MyBase.Channel.SubGetSubSystemCombobox(sub_app_system_no)
        End Function
        
        Public Function TskGetAllSystem(ByVal app_system_no As String, ByVal tsk_sub_system_no As String, ByVal tsk_task_no As String, ByVal tsk_task_name As String, ByVal tsk_display_order As String, ByVal tsk_task_flag_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.TskGetAllSystem
            Return MyBase.Channel.TskGetAllSystem(app_system_no, tsk_sub_system_no, tsk_task_no, tsk_task_name, tsk_display_order, tsk_task_flag_no)
        End Function
        
        Public Function TskQueryByPK(ByRef pk_tsk_task_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.TskQueryByPK
            Return MyBase.Channel.TskQueryByPK(pk_tsk_task_no)
        End Function
        
        Public Function TskInsert(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.TskInsert
            Return MyBase.Channel.TskInsert(ds)
        End Function
        
        Public Function TskDelete(ByRef pk_tsk_task_no As String) As Integer Implements ArmServiceReference.IArmService.TskDelete
            Return MyBase.Channel.TskDelete(pk_tsk_task_no)
        End Function
        
        Public Function TskUpdate(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.TskUpdate
            Return MyBase.Channel.TskUpdate(ds)
        End Function
        
        Public Function TskGetTskSystemCombobox(ByVal tsk_sub_system_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.TskGetTskSystemCombobox
            Return MyBase.Channel.TskGetTskSystemCombobox(tsk_sub_system_no)
        End Function
        
        Public Function FunGetAllSystem(ByVal app_system_no As String, ByVal sub_system_no As String, ByVal fun_task_no As String, ByVal fun_function_no As String, ByVal fun_function_name As String, ByVal fun_content As String, ByVal fun_special_flag As String, ByVal fun_display_order As String, ByVal fun_flag_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.FunGetAllSystem
            Return MyBase.Channel.FunGetAllSystem(app_system_no, sub_system_no, fun_task_no, fun_function_no, fun_function_name, fun_content, fun_special_flag, fun_display_order, fun_flag_no)
        End Function
        
        Public Function FunQueryByPK(ByRef pk_fun_function_no As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.FunQueryByPK
            Return MyBase.Channel.FunQueryByPK(pk_fun_function_no)
        End Function
        
        Public Function FunQueryByLogin() As System.Data.DataSet Implements ArmServiceReference.IArmService.FunQueryByLogin
            Return MyBase.Channel.FunQueryByLogin
        End Function
        
        Public Function FunInsert(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.FunInsert
            Return MyBase.Channel.FunInsert(ds)
        End Function
        
        Public Function FunDelete(ByRef pk_fun_function_no As String) As Integer Implements ArmServiceReference.IArmService.FunDelete
            Return MyBase.Channel.FunDelete(pk_fun_function_no)
        End Function
        
        Public Function FunUpdate(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.FunUpdate
            Return MyBase.Channel.FunUpdate(ds)
        End Function
        
        Public Function insertLogonDate(ByVal ip As String, ByVal employeeCode As String) As Integer Implements ArmServiceReference.IArmService.insertLogonDate
            Return MyBase.Channel.insertLogonDate(ip, employeeCode)
        End Function
        
        Public Function updateLogoutDate(ByVal ip As String, ByVal employeeCode As String) As Integer Implements ArmServiceReference.IArmService.updateLogoutDate
            Return MyBase.Channel.updateLogoutDate(ip, employeeCode)
        End Function
        
        Public Function queryIP() As System.Data.DataSet Implements ArmServiceReference.IArmService.queryIP
            Return MyBase.Channel.queryIP
        End Function
        
        Public Function insertLogonDateBySystem(ByVal systemNo As String, ByVal loginDate As String, ByVal ip As String, ByVal employeeCode As String, ByVal agentCode As String, ByVal machineName As String) As Integer Implements ArmServiceReference.IArmService.insertLogonDateBySystem
            Return MyBase.Channel.insertLogonDateBySystem(systemNo, loginDate, ip, employeeCode, agentCode, machineName)
        End Function
        
        Public Function updateLogoutDateBySystem(ByVal systemNo As String, ByVal loginDate As String, ByVal ip As String, ByVal employeeCode As String, ByVal agentCode As String, ByVal machineName As String) As Integer Implements ArmServiceReference.IArmService.updateLogoutDateBySystem
            Return MyBase.Channel.updateLogoutDateBySystem(systemNo, loginDate, ip, employeeCode, agentCode, machineName)
        End Function
        
        Public Function queryIPBySystem(ByVal systemNo As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryIPBySystem
            Return MyBase.Channel.queryIPBySystem(systemNo)
        End Function
        
        Public Function queryEmployeeRoleData(ByVal role As String, ByVal employeeCode As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryEmployeeRoleData
            Return MyBase.Channel.queryEmployeeRoleData(role, employeeCode)
        End Function
        
        Public Function getPassword(ByVal user As String) As String Implements ArmServiceReference.IArmService.getPassword
            Return MyBase.Channel.getPassword(user)
        End Function
        
        Public Function saveLogonFailure(ByVal employeeCode As String, ByVal ip As String, ByVal machineName As String) As Integer Implements ArmServiceReference.IArmService.saveLogonFailure
            Return MyBase.Channel.saveLogonFailure(employeeCode, ip, machineName)
        End Function
        
        Public Function insertProfile(ByVal ds As System.Data.DataSet) As String Implements ArmServiceReference.IArmService.insertProfile
            Return MyBase.Channel.insertProfile(ds)
        End Function
        
        Public Function deleteProfile(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File_Name As String) As Integer Implements ArmServiceReference.IArmService.deleteProfile
            Return MyBase.Channel.deleteProfile(pk_System_No, pk_Employee_Code, pk_Sub_File_Name)
        End Function
        
        Public Function queryProfileByPk(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File_Name As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryProfileByPk
            Return MyBase.Channel.queryProfileByPk(pk_System_No, pk_Employee_Code, pk_Sub_File_Name)
        End Function
        
        Public Function queryProfile(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal flag As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryProfile
            Return MyBase.Channel.queryProfile(pk_System_No, pk_Employee_Code, flag)
        End Function
        
        Public Function updateProfileDefault(ByVal pk_System_No As String, ByVal pk_Employee_Code As String, ByVal pk_Sub_File As String, ByVal flag As String) As Integer Implements ArmServiceReference.IArmService.updateProfileDefault
            Return MyBase.Channel.updateProfileDefault(pk_System_No, pk_Employee_Code, pk_Sub_File, flag)
        End Function
        
        Public Function RoleQueryByEmployee(ByVal Employee_Code As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.RoleQueryByEmployee
            Return MyBase.Channel.RoleQueryByEmployee(Employee_Code)
        End Function
        
        Public Function EmployeeQueryByRole(ByVal Role_Id As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.EmployeeQueryByRole
            Return MyBase.Channel.EmployeeQueryByRole(Role_Id)
        End Function
        
        Public Function EmployeeQueryByFunction(ByVal Fun_Function_No As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.EmployeeQueryByFunction
            Return MyBase.Channel.EmployeeQueryByFunction(Fun_Function_No)
        End Function
        
        Public Function insertFunRecord(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.insertFunRecord
            Return MyBase.Channel.insertFunRecord(ds)
        End Function
        
        Public Function insertArmAgentAuth(ByVal ds As System.Data.DataSet) As Integer Implements ArmServiceReference.IArmService.insertArmAgentAuth
            Return MyBase.Channel.insertArmAgentAuth(ds)
        End Function
        
        Public Function deleteArmAgentAuth(ByVal employeeCode As String, ByVal agentCode As String, ByVal roleId As String, ByVal effectDate As String) As Integer Implements ArmServiceReference.IArmService.deleteArmAgentAuth
            Return MyBase.Channel.deleteArmAgentAuth(employeeCode, agentCode, roleId, effectDate)
        End Function
        
        Public Function queryByAgentEmployeeCode(ByRef pk_employee_code As String, ByRef pk_agent_code As String, ByVal role_id As String, ByVal effect_date As String, ByVal end_date As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryByAgentEmployeeCode
            Return MyBase.Channel.queryByAgentEmployeeCode(pk_employee_code, pk_agent_code, role_id, effect_date, end_date)
        End Function
        
        Public Function queryArmRecord(ByVal employeeCode As String, ByVal functionNo As String, ByVal startDate As String, ByVal endDate As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryArmRecord
            Return MyBase.Channel.queryArmRecord(employeeCode, functionNo, startDate, endDate)
        End Function
        
        Public Function queryRoleRightsByMemberOf(ByVal userMemberOf As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.queryRoleRightsByMemberOf
            Return MyBase.Channel.queryRoleRightsByMemberOf(userMemberOf)
        End Function
        
        Public Function ArmLogonFailureQueryLoginFailure(ByVal str_StartDay As String, ByVal str_EndDay As String) As System.Data.DataSet Implements ArmServiceReference.IArmService.ArmLogonFailureQueryLoginFailure
            Return MyBase.Channel.ArmLogonFailureQueryLoginFailure(str_StartDay, str_EndDay)
        End Function
    End Class
End Namespace
