'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SncServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SncServiceReference.ISncService")>  _
    Public Interface ISncService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISncService/getTWYearApiSequentialNo", ReplyAction:="http://tempuri.org/ISncService/getTWYearApiSequentialNoResponse")>  _
        Function getTWYearApiSequentialNo(ByVal strVKey As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISncService/getCmmSerialNoTx", ReplyAction:="http://tempuri.org/ISncService/getCmmSerialNoTxResponse")>  _
        Function getCmmSerialNoTx(ByVal vType As String, ByVal strVKey As String, ByVal vMinNo As String, ByVal vMaxNo As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISncServiceChannel
        Inherits SncServiceReference.ISncService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SncServiceClient
        Inherits System.ServiceModel.ClientBase(Of SncServiceReference.ISncService)
        Implements SncServiceReference.ISncService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getTWYearApiSequentialNo(ByVal strVKey As String) As String Implements SncServiceReference.ISncService.getTWYearApiSequentialNo
            Return MyBase.Channel.getTWYearApiSequentialNo(strVKey)
        End Function
        
        Public Function getCmmSerialNoTx(ByVal vType As String, ByVal strVKey As String, ByVal vMinNo As String, ByVal vMaxNo As String) As String Implements SncServiceReference.ISncService.getCmmSerialNoTx
            Return MyBase.Channel.getCmmSerialNoTx(vType, strVKey, vMinNo, vMaxNo)
        End Function
    End Class
End Namespace
