'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FtmServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FtmServiceReference.IFtmService")>  _
    Public Interface IFtmService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/uploadNewFile", ReplyAction:="http://tempuri.org/IFtmService/uploadNewFileResponse")>  _
        Function uploadNewFile(ByRef data As System.Data.DataSet, ByRef fileVersionData As System.Data.DataSet) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/downloadFile", ReplyAction:="http://tempuri.org/IFtmService/downloadFileResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of Object, Object)))>  _
        Function downloadFile(ByRef FID As String, ByRef old_file_name As Boolean) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/downloadFiles", ReplyAction:="http://tempuri.org/IFtmService/downloadFilesResponse")>  _
        Function downloadFiles(ByRef FIDs() As String, ByRef old_file_name As Boolean) As System.Collections.Generic.Dictionary(Of Object, Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/getImageThumb", ReplyAction:="http://tempuri.org/IFtmService/getImageThumbResponse")>  _
        Function getImageThumb(ByRef FID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/doMyReport", ReplyAction:="http://tempuri.org/IFtmService/doMyReportResponse")>  _
        Sub doMyReport(ByRef FID As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/uploadNewFilePath", ReplyAction:="http://tempuri.org/IFtmService/uploadNewFilePathResponse")>  _
        Function uploadNewFilePath(ByVal inUNCPathTag As String, ByVal inAccessIDTag As String, ByVal inAccessPWTag As String, ByRef data As System.Data.DataSet, ByRef fileVersionData As System.Data.DataSet) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFtmService/downloadFilePath", ReplyAction:="http://tempuri.org/IFtmService/downloadFilePathResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of Object, Object)))>  _
        Function downloadFilePath(ByRef FID As String, ByVal inUNCPathTag As String, ByVal inAccessIDTag As String, ByVal inAccessPWTag As String, ByVal inExtensionName As String, ByRef old_file_name As Boolean) As Object()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IFtmServiceChannel
        Inherits FtmServiceReference.IFtmService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FtmServiceClient
        Inherits System.ServiceModel.ClientBase(Of FtmServiceReference.IFtmService)
        Implements FtmServiceReference.IFtmService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function uploadNewFile(ByRef data As System.Data.DataSet, ByRef fileVersionData As System.Data.DataSet) As String() Implements FtmServiceReference.IFtmService.uploadNewFile
            Return MyBase.Channel.uploadNewFile(data, fileVersionData)
        End Function
        
        Public Function downloadFile(ByRef FID As String, ByRef old_file_name As Boolean) As Object() Implements FtmServiceReference.IFtmService.downloadFile
            Return MyBase.Channel.downloadFile(FID, old_file_name)
        End Function
        
        Public Function downloadFiles(ByRef FIDs() As String, ByRef old_file_name As Boolean) As System.Collections.Generic.Dictionary(Of Object, Object) Implements FtmServiceReference.IFtmService.downloadFiles
            Return MyBase.Channel.downloadFiles(FIDs, old_file_name)
        End Function
        
        Public Function getImageThumb(ByRef FID As String) As Byte() Implements FtmServiceReference.IFtmService.getImageThumb
            Return MyBase.Channel.getImageThumb(FID)
        End Function
        
        Public Sub doMyReport(ByRef FID As Integer) Implements FtmServiceReference.IFtmService.doMyReport
            MyBase.Channel.doMyReport(FID)
        End Sub
        
        Public Function uploadNewFilePath(ByVal inUNCPathTag As String, ByVal inAccessIDTag As String, ByVal inAccessPWTag As String, ByRef data As System.Data.DataSet, ByRef fileVersionData As System.Data.DataSet) As String() Implements FtmServiceReference.IFtmService.uploadNewFilePath
            Return MyBase.Channel.uploadNewFilePath(inUNCPathTag, inAccessIDTag, inAccessPWTag, data, fileVersionData)
        End Function
        
        Public Function downloadFilePath(ByRef FID As String, ByVal inUNCPathTag As String, ByVal inAccessIDTag As String, ByVal inAccessPWTag As String, ByVal inExtensionName As String, ByRef old_file_name As Boolean) As Object() Implements FtmServiceReference.IFtmService.downloadFilePath
            Return MyBase.Channel.downloadFilePath(FID, inUNCPathTag, inAccessIDTag, inAccessPWTag, inExtensionName, old_file_name)
        End Function
    End Class
End Namespace
