'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IccServiceLReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IccServiceLReference.IIccServiceL")>  _
    Public Interface IIccServiceL
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/DoWork", ReplyAction:="http://tempuri.org/IIccServiceL/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByCond"& _ 
            "", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByCond"& _ 
            "Response")>  _
        Function queryICCHealthUploadandICCInoculationUploadByCond(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByPage"& _ 
            "1Cond", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByPage"& _ 
            "1CondResponse")>  _
        Function queryICCHealthUploadandICCInoculationUploadByPage1Cond(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByCond"& _ 
            "2", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCHealthUploadandICCInoculationUploadByCond"& _ 
            "2Response")>  _
        Function queryICCHealthUploadandICCInoculationUploadByCond2(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCHealthUpload", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCHealthUploadResponse")>  _
        Function updateICCHealthUpload(ByVal strCancelUser As String, ByVal strChartNo As String, ByVal strSourceSn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCInoculationUpload", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCInoculationUploadResponse")>  _
        Function updateICCInoculationUpload(ByVal strCancelUser As String, ByVal strChartNo As String, ByVal strSourceSn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteICCInoculationUploadBS", ReplyAction:="http://tempuri.org/IIccServiceL/deleteICCInoculationUploadBSResponse")>  _
        Sub deleteICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryDeletekeystateByInoculationSn", ReplyAction:="http://tempuri.org/IIccServiceL/queryDeletekeystateByInoculationSnResponse")>  _
        Function queryDeletekeystateByInoculationSn(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCInoculationUpload", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCInoculationUploadResponse")>  _
        Function insertICCInoculationUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCHealthOrderUpload", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCHealthOrderUploadResponse")>  _
        Function insertICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCMustFieldVerify", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCMustFieldVerifyResponse")>  _
        Function queryICCMustFieldVerify(ByVal strTreatmentCategoryId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCMustFieldVerify", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCMustFieldVerifyResponse")>  _
        Function insertICCMustFieldVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCMustFieldVerify", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCMustFieldVerifyResponse")>  _
        Function updateICCMustFieldVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteCCMustFieldVerify", ReplyAction:="http://tempuri.org/IIccServiceL/deleteCCMustFieldVerifyResponse")>  _
        Function deleteCCMustFieldVerify(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccFieldLengthVerify", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccFieldLengthVerifyResponse")>  _
        Function queryIccFieldLengthVerify(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccFieldLengthVerify", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccFieldLengthVerifyResponse")>  _
        Function insertIccFieldLengthVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccFieldLengthVerify", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccFieldLengthVerifyResponse")>  _
        Function updateIccFieldLengthVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccFieldLengthVerify", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccFieldLengthVerifyResponse")>  _
        Function deleteIccFieldLengthVerify(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccSelfVerify", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccSelfVerifyResponse")>  _
        Function queryIccSelfVerify(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccSelfVerify", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccSelfVerifyResponse")>  _
        Function insertIccSelfVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccSelfVerify", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccSelfVerifyResponse")>  _
        Function updateIccSelfVerify(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccSelfVerify", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccSelfVerifyResponse")>  _
        Function deleteIccSelfVerify(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccInteractVerify1ById", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccInteractVerify1ByIdResponse")>  _
        Function queryIccInteractVerify1ById(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccInteractVerify1", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccInteractVerify1Response")>  _
        Function insertIccInteractVerify1(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccInteractVerify1", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccInteractVerify1Response")>  _
        Function updateIccInteractVerify1(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify1", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify1Response")>  _
        Function deleteIccInteractVerify1(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccInteractVerify2ById", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccInteractVerify2ByIdResponse")>  _
        Function queryIccInteractVerify2ById(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccInteractVerify2", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccInteractVerify2Response")>  _
        Function insertIccInteractVerify2(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccInteractVerify2", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccInteractVerify2Response")>  _
        Function updateIccInteractVerify2(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify2", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify2Response")>  _
        Function deleteIccInteractVerify2(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccInteractVerify3ById", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccInteractVerify3ByIdResponse")>  _
        Function queryIccInteractVerify3ById(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccInteractVerify3", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccInteractVerify3Response")>  _
        Function insertIccInteractVerify3(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccInteractVerify3", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccInteractVerify3Response")>  _
        Function updateIccInteractVerify3(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify3", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify3Response")>  _
        Function deleteIccInteractVerify3(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryIccInteractVerify4ById", ReplyAction:="http://tempuri.org/IIccServiceL/queryIccInteractVerify4ByIdResponse")>  _
        Function queryIccInteractVerify4ById(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertIccInteractVerify4", ReplyAction:="http://tempuri.org/IIccServiceL/insertIccInteractVerify4Response")>  _
        Function insertIccInteractVerify4(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateIccInteractVerify4", ReplyAction:="http://tempuri.org/IIccServiceL/updateIccInteractVerify4Response")>  _
        Function updateIccInteractVerify4(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify4", ReplyAction:="http://tempuri.org/IIccServiceL/deleteIccInteractVerify4Response")>  _
        Function deleteIccInteractVerify4(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCOnlineCheckById", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCOnlineCheckByIdResponse")>  _
        Function queryICCOnlineCheckById(ByVal strId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCOnlineCheckById", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCOnlineCheckByIdResponse")>  _
        Function insertICCOnlineCheckById(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCOnlineCheckById", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCOnlineCheckByIdResponse")>  _
        Function updateICCOnlineCheckById(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteICCOnlineCheckById", ReplyAction:="http://tempuri.org/IIccServiceL/deleteICCOnlineCheckByIdResponse")>  _
        Function deleteICCOnlineCheckById(ByVal pkid As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCBacterinUpload", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCBacterinUploadResponse")>  _
        Function insertICCBacterinUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCInoculationUploadBS", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCInoculationUploadBSResponse")>  _
        Function updateICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCInoculationUploadByPK", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCInoculationUploadByPKResponse")>  _
        Function queryICCInoculationUploadByPK(ByVal strInoculationSn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/confirmICCInoculationUploadBS", ReplyAction:="http://tempuri.org/IIccServiceL/confirmICCInoculationUploadBSResponse")>  _
        Function confirmICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/insertICCOrderUpload", ReplyAction:="http://tempuri.org/IIccServiceL/insertICCOrderUploadResponse")>  _
        Function insertICCOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCHealthOrderUpload", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCHealthOrderUploadResponse")>  _
        Function updateICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCHealthOrderUpload", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCHealthOrderUploadResponse")>  _
        Function queryICCHealthOrderUpload(ByVal strHealthSn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/confirmICCHealthOrderUpload", ReplyAction:="http://tempuri.org/IIccServiceL/confirmICCHealthOrderUploadResponse")>  _
        Function confirmICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCInoculationUpload", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCInoculationUploadResponse")>  _
        Function queryICCInoculationUpload(ByVal strInoculationSn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/deleteICCInoculationUploadByPk", ReplyAction:="http://tempuri.org/IIccServiceL/deleteICCInoculationUploadByPkResponse")>  _
        Function deleteICCInoculationUploadByPk(ByVal pkId As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryA24ByOutpatient_Sn_L", ReplyAction:="http://tempuri.org/IIccServiceL/queryA24ByOutpatient_Sn_LResponse")>  _
        Function queryA24ByOutpatient_Sn_L(ByVal strInoculationSn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/updateICCInoculationUploadByPk_L", ReplyAction:="http://tempuri.org/IIccServiceL/updateICCInoculationUploadByPk_LResponse")>  _
        Function updateICCInoculationUploadByPk_L(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/queryICCInoculationSn_L", ReplyAction:="http://tempuri.org/IIccServiceL/queryICCInoculationSn_LResponse")>  _
        Function queryICCInoculationSn_L(ByVal strChartNo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/QueryIccCloudDrugPatientByCond", ReplyAction:="http://tempuri.org/IIccServiceL/QueryIccCloudDrugPatientByCondResponse")>  _
        Function QueryIccCloudDrugPatientByCond(ByVal strIdno As String, ByVal dMedicalDate As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/InsertIccCloudDrugPatient", ReplyAction:="http://tempuri.org/IIccServiceL/InsertIccCloudDrugPatientResponse")>  _
        Function InsertIccCloudDrugPatient(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/DeleteIccCloudDrugPatientByPK", ReplyAction:="http://tempuri.org/IIccServiceL/DeleteIccCloudDrugPatientByPKResponse")>  _
        Function DeleteIccCloudDrugPatientByPK(ByVal strIdno As String, ByVal dMedicalDate As Date) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/UpdateIccCloudDrugPatient", ReplyAction:="http://tempuri.org/IIccServiceL/UpdateIccCloudDrugPatientResponse")>  _
        Function UpdateIccCloudDrugPatient(ByVal dsSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/QueryIccAlertRecByCond", ReplyAction:="http://tempuri.org/IIccServiceL/QueryIccAlertRecByCondResponse")>  _
        Function QueryIccAlertRecByCond(ByRef Query_Type As String, ByVal ST_Visit_Date As String, ByVal ED_Visit_Date As String, ByVal Chart_No As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccServiceL/QueryIccCloudPatientQryByCond", ReplyAction:="http://tempuri.org/IIccServiceL/QueryIccCloudPatientQryByCondResponse")>  _
        Function QueryIccCloudPatientQryByCond(ByRef Query_Type As String, ByVal dCreate_Time As String, ByVal dModified_Time As String, ByVal IdNo As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IIccServiceLChannel
        Inherits IccServiceLReference.IIccServiceL, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IccServiceLClient
        Inherits System.ServiceModel.ClientBase(Of IccServiceLReference.IIccServiceL)
        Implements IccServiceLReference.IIccServiceL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements IccServiceLReference.IIccServiceL.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function queryICCHealthUploadandICCInoculationUploadByCond(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCHealthUploadandICCInoculationUploadByCond
            Return MyBase.Channel.queryICCHealthUploadandICCInoculationUploadByCond(strUploadTypeId, strChartNo, strSourceSn, strCreateSearchTime, strA00, strA01, strA17, strIsBabyStool, strA12)
        End Function
        
        Public Function queryICCHealthUploadandICCInoculationUploadByPage1Cond(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCHealthUploadandICCInoculationUploadByPage1Cond
            Return MyBase.Channel.queryICCHealthUploadandICCInoculationUploadByPage1Cond(strUploadTypeId, strChartNo, strSourceSn, strCreateSearchTime, strA00, strA01, strA17, strIsBabyStool, strA12)
        End Function
        
        Public Function queryICCHealthUploadandICCInoculationUploadByCond2(ByVal strUploadTypeId As String, ByVal strChartNo As String, ByVal strSourceSn As String, ByVal strCreateSearchTime As String, ByVal strA00 As String, ByVal strA01 As String, ByVal strA17 As String, ByVal strIsBabyStool As String, ByVal strA12 As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCHealthUploadandICCInoculationUploadByCond2
            Return MyBase.Channel.queryICCHealthUploadandICCInoculationUploadByCond2(strUploadTypeId, strChartNo, strSourceSn, strCreateSearchTime, strA00, strA01, strA17, strIsBabyStool, strA12)
        End Function
        
        Public Function updateICCHealthUpload(ByVal strCancelUser As String, ByVal strChartNo As String, ByVal strSourceSn As String) As Integer Implements IccServiceLReference.IIccServiceL.updateICCHealthUpload
            Return MyBase.Channel.updateICCHealthUpload(strCancelUser, strChartNo, strSourceSn)
        End Function
        
        Public Function updateICCInoculationUpload(ByVal strCancelUser As String, ByVal strChartNo As String, ByVal strSourceSn As String) As Integer Implements IccServiceLReference.IIccServiceL.updateICCInoculationUpload
            Return MyBase.Channel.updateICCInoculationUpload(strCancelUser, strChartNo, strSourceSn)
        End Function
        
        Public Sub deleteICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet) Implements IccServiceLReference.IIccServiceL.deleteICCInoculationUploadBS
            MyBase.Channel.deleteICCInoculationUploadBS(dsSaveData)
        End Sub
        
        Public Function queryDeletekeystateByInoculationSn(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryDeletekeystateByInoculationSn
            Return MyBase.Channel.queryDeletekeystateByInoculationSn(strId)
        End Function
        
        Public Function insertICCInoculationUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCInoculationUpload
            Return MyBase.Channel.insertICCInoculationUpload(dsSaveData)
        End Function
        
        Public Function insertICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCHealthOrderUpload
            Return MyBase.Channel.insertICCHealthOrderUpload(dsSaveData)
        End Function
        
        Public Function queryICCMustFieldVerify(ByVal strTreatmentCategoryId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCMustFieldVerify
            Return MyBase.Channel.queryICCMustFieldVerify(strTreatmentCategoryId)
        End Function
        
        Public Function insertICCMustFieldVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCMustFieldVerify
            Return MyBase.Channel.insertICCMustFieldVerify(ds)
        End Function
        
        Public Function updateICCMustFieldVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateICCMustFieldVerify
            Return MyBase.Channel.updateICCMustFieldVerify(ds)
        End Function
        
        Public Function deleteCCMustFieldVerify(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteCCMustFieldVerify
            Return MyBase.Channel.deleteCCMustFieldVerify(pkid)
        End Function
        
        Public Function queryIccFieldLengthVerify(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccFieldLengthVerify
            Return MyBase.Channel.queryIccFieldLengthVerify(strId)
        End Function
        
        Public Function insertIccFieldLengthVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccFieldLengthVerify
            Return MyBase.Channel.insertIccFieldLengthVerify(ds)
        End Function
        
        Public Function updateIccFieldLengthVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccFieldLengthVerify
            Return MyBase.Channel.updateIccFieldLengthVerify(ds)
        End Function
        
        Public Function deleteIccFieldLengthVerify(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccFieldLengthVerify
            Return MyBase.Channel.deleteIccFieldLengthVerify(pkid)
        End Function
        
        Public Function queryIccSelfVerify(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccSelfVerify
            Return MyBase.Channel.queryIccSelfVerify(strId)
        End Function
        
        Public Function insertIccSelfVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccSelfVerify
            Return MyBase.Channel.insertIccSelfVerify(ds)
        End Function
        
        Public Function updateIccSelfVerify(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccSelfVerify
            Return MyBase.Channel.updateIccSelfVerify(ds)
        End Function
        
        Public Function deleteIccSelfVerify(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccSelfVerify
            Return MyBase.Channel.deleteIccSelfVerify(pkid)
        End Function
        
        Public Function queryIccInteractVerify1ById(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccInteractVerify1ById
            Return MyBase.Channel.queryIccInteractVerify1ById(strId)
        End Function
        
        Public Function insertIccInteractVerify1(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccInteractVerify1
            Return MyBase.Channel.insertIccInteractVerify1(ds)
        End Function
        
        Public Function updateIccInteractVerify1(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccInteractVerify1
            Return MyBase.Channel.updateIccInteractVerify1(ds)
        End Function
        
        Public Function deleteIccInteractVerify1(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccInteractVerify1
            Return MyBase.Channel.deleteIccInteractVerify1(pkid)
        End Function
        
        Public Function queryIccInteractVerify2ById(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccInteractVerify2ById
            Return MyBase.Channel.queryIccInteractVerify2ById(strId)
        End Function
        
        Public Function insertIccInteractVerify2(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccInteractVerify2
            Return MyBase.Channel.insertIccInteractVerify2(ds)
        End Function
        
        Public Function updateIccInteractVerify2(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccInteractVerify2
            Return MyBase.Channel.updateIccInteractVerify2(ds)
        End Function
        
        Public Function deleteIccInteractVerify2(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccInteractVerify2
            Return MyBase.Channel.deleteIccInteractVerify2(pkid)
        End Function
        
        Public Function queryIccInteractVerify3ById(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccInteractVerify3ById
            Return MyBase.Channel.queryIccInteractVerify3ById(strId)
        End Function
        
        Public Function insertIccInteractVerify3(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccInteractVerify3
            Return MyBase.Channel.insertIccInteractVerify3(ds)
        End Function
        
        Public Function updateIccInteractVerify3(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccInteractVerify3
            Return MyBase.Channel.updateIccInteractVerify3(ds)
        End Function
        
        Public Function deleteIccInteractVerify3(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccInteractVerify3
            Return MyBase.Channel.deleteIccInteractVerify3(pkid)
        End Function
        
        Public Function queryIccInteractVerify4ById(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryIccInteractVerify4ById
            Return MyBase.Channel.queryIccInteractVerify4ById(strId)
        End Function
        
        Public Function insertIccInteractVerify4(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertIccInteractVerify4
            Return MyBase.Channel.insertIccInteractVerify4(ds)
        End Function
        
        Public Function updateIccInteractVerify4(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateIccInteractVerify4
            Return MyBase.Channel.updateIccInteractVerify4(ds)
        End Function
        
        Public Function deleteIccInteractVerify4(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteIccInteractVerify4
            Return MyBase.Channel.deleteIccInteractVerify4(pkid)
        End Function
        
        Public Function queryICCOnlineCheckById(ByVal strId As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCOnlineCheckById
            Return MyBase.Channel.queryICCOnlineCheckById(strId)
        End Function
        
        Public Function insertICCOnlineCheckById(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCOnlineCheckById
            Return MyBase.Channel.insertICCOnlineCheckById(ds)
        End Function
        
        Public Function updateICCOnlineCheckById(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateICCOnlineCheckById
            Return MyBase.Channel.updateICCOnlineCheckById(ds)
        End Function
        
        Public Function deleteICCOnlineCheckById(ByVal pkid As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteICCOnlineCheckById
            Return MyBase.Channel.deleteICCOnlineCheckById(pkid)
        End Function
        
        Public Function insertICCBacterinUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCBacterinUpload
            Return MyBase.Channel.insertICCBacterinUpload(dsSaveData)
        End Function
        
        Public Function updateICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateICCInoculationUploadBS
            Return MyBase.Channel.updateICCInoculationUploadBS(dsSaveData)
        End Function
        
        Public Function queryICCInoculationUploadByPK(ByVal strInoculationSn As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCInoculationUploadByPK
            Return MyBase.Channel.queryICCInoculationUploadByPK(strInoculationSn)
        End Function
        
        Public Function confirmICCInoculationUploadBS(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.confirmICCInoculationUploadBS
            Return MyBase.Channel.confirmICCInoculationUploadBS(dsSaveData)
        End Function
        
        Public Function insertICCOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.insertICCOrderUpload
            Return MyBase.Channel.insertICCOrderUpload(dsSaveData)
        End Function
        
        Public Function updateICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateICCHealthOrderUpload
            Return MyBase.Channel.updateICCHealthOrderUpload(dsSaveData)
        End Function
        
        Public Function queryICCHealthOrderUpload(ByVal strHealthSn As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCHealthOrderUpload
            Return MyBase.Channel.queryICCHealthOrderUpload(strHealthSn)
        End Function
        
        Public Function confirmICCHealthOrderUpload(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.confirmICCHealthOrderUpload
            Return MyBase.Channel.confirmICCHealthOrderUpload(dsSaveData)
        End Function
        
        Public Function queryICCInoculationUpload(ByVal strInoculationSn As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCInoculationUpload
            Return MyBase.Channel.queryICCInoculationUpload(strInoculationSn)
        End Function
        
        Public Function deleteICCInoculationUploadByPk(ByVal pkId As String) As Integer Implements IccServiceLReference.IIccServiceL.deleteICCInoculationUploadByPk
            Return MyBase.Channel.deleteICCInoculationUploadByPk(pkId)
        End Function
        
        Public Function queryA24ByOutpatient_Sn_L(ByVal strInoculationSn As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryA24ByOutpatient_Sn_L
            Return MyBase.Channel.queryA24ByOutpatient_Sn_L(strInoculationSn)
        End Function
        
        Public Function updateICCInoculationUploadByPk_L(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.updateICCInoculationUploadByPk_L
            Return MyBase.Channel.updateICCInoculationUploadByPk_L(dsSaveData)
        End Function
        
        Public Function queryICCInoculationSn_L(ByVal strChartNo As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.queryICCInoculationSn_L
            Return MyBase.Channel.queryICCInoculationSn_L(strChartNo)
        End Function
        
        Public Function QueryIccCloudDrugPatientByCond(ByVal strIdno As String, ByVal dMedicalDate As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.QueryIccCloudDrugPatientByCond
            Return MyBase.Channel.QueryIccCloudDrugPatientByCond(strIdno, dMedicalDate)
        End Function
        
        Public Function InsertIccCloudDrugPatient(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.InsertIccCloudDrugPatient
            Return MyBase.Channel.InsertIccCloudDrugPatient(dsSaveData)
        End Function
        
        Public Function DeleteIccCloudDrugPatientByPK(ByVal strIdno As String, ByVal dMedicalDate As Date) As Integer Implements IccServiceLReference.IIccServiceL.DeleteIccCloudDrugPatientByPK
            Return MyBase.Channel.DeleteIccCloudDrugPatientByPK(strIdno, dMedicalDate)
        End Function
        
        Public Function UpdateIccCloudDrugPatient(ByVal dsSaveData As System.Data.DataSet) As Integer Implements IccServiceLReference.IIccServiceL.UpdateIccCloudDrugPatient
            Return MyBase.Channel.UpdateIccCloudDrugPatient(dsSaveData)
        End Function
        
        Public Function QueryIccAlertRecByCond(ByRef Query_Type As String, ByVal ST_Visit_Date As String, ByVal ED_Visit_Date As String, ByVal Chart_No As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.QueryIccAlertRecByCond
            Return MyBase.Channel.QueryIccAlertRecByCond(Query_Type, ST_Visit_Date, ED_Visit_Date, Chart_No)
        End Function
        
        Public Function QueryIccCloudPatientQryByCond(ByRef Query_Type As String, ByVal dCreate_Time As String, ByVal dModified_Time As String, ByVal IdNo As String) As System.Data.DataSet Implements IccServiceLReference.IIccServiceL.QueryIccCloudPatientQryByCond
            Return MyBase.Channel.QueryIccCloudPatientQryByCond(Query_Type, dCreate_Time, dModified_Time, IdNo)
        End Function
    End Class
End Namespace
