'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NfcServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="NfcServiceReference.INfcService")>  _
    Public Interface INfcService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/readUIMessage24HrAuto", ReplyAction:="http://tempuri.org/INfcService/readUIMessage24HrAutoResponse")>  _
        Function readUIMessage24HrAuto(ByVal empNO As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/readUIMessage24Hr", ReplyAction:="http://tempuri.org/INfcService/readUIMessage24HrResponse")>  _
        Function readUIMessage24Hr(ByVal empNO As String, ByVal depNo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/readUIMessageAuto", ReplyAction:="http://tempuri.org/INfcService/readUIMessageAutoResponse")>  _
        Function readUIMessageAuto(ByVal empNO As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/readUIMessage", ReplyAction:="http://tempuri.org/INfcService/readUIMessageResponse")>  _
        Function readUIMessage(ByVal empNO As String, ByVal depNo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyAllUI", ReplyAction:="http://tempuri.org/INfcService/NotifyAllUIResponse")>  _
        Sub NotifyAllUI(ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyAllUIExternal", ReplyAction:="http://tempuri.org/INfcService/NotifyAllUIExternalResponse")>  _
        Sub NotifyAllUIExternal(ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyDepUI", ReplyAction:="http://tempuri.org/INfcService/NotifyDepUIResponse")>  _
        Sub NotifyDepUI(ByVal empDept As String, ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyDepUIExternal", ReplyAction:="http://tempuri.org/INfcService/NotifyDepUIExternalResponse")>  _
        Sub NotifyDepUIExternal(ByVal empDept As String, ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUIMulti", ReplyAction:="http://tempuri.org/INfcService/NotifyUIMultiResponse")>  _
        Sub NotifyUIMulti(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUIMultiExternal", ReplyAction:="http://tempuri.org/INfcService/NotifyUIMultiExternalResponse")>  _
        Sub NotifyUIMultiExternal(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUI", ReplyAction:="http://tempuri.org/INfcService/NotifyUIResponse")>  _
        Sub NotifyUI(ByVal drEmpNo As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUIExternal", ReplyAction:="http://tempuri.org/INfcService/NotifyUIExternalResponse")>  _
        Sub NotifyUIExternal(ByVal drEmpNo As String, ByVal subject As String, ByVal msg As String, ByVal external As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyMailMulti", ReplyAction:="http://tempuri.org/INfcService/NotifyMailMultiResponse")>  _
        Sub NotifyMailMulti(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyMailMultiReply", ReplyAction:="http://tempuri.org/INfcService/NotifyMailMultiReplyResponse")>  _
        Sub NotifyMailMultiReply(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyMail", ReplyAction:="http://tempuri.org/INfcService/NotifyMailResponse")>  _
        Sub NotifyMail(ByVal EmpMail As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyMailReply", ReplyAction:="http://tempuri.org/INfcService/NotifyMailReplyResponse")>  _
        Sub NotifyMailReply(ByVal EmpMail As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifySMS", ReplyAction:="http://tempuri.org/INfcService/NotifySMSResponse")>  _
        Sub NotifySMS(ByVal drEmpNo As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifySMSMulti", ReplyAction:="http://tempuri.org/INfcService/NotifySMSMultiResponse")>  _
        Sub NotifySMSMulti(ByVal drEmpNo() As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifySMSMultiWithSubject", ReplyAction:="http://tempuri.org/INfcService/NotifySMSMultiWithSubjectResponse")>  _
        Sub NotifySMSMultiWithSubject(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyByFunctionNo", ReplyAction:="http://tempuri.org/INfcService/NotifyByFunctionNoResponse")>  _
        Sub NotifyByFunctionNo(ByVal inSystemNo As String, ByVal inSubSystemNo As String, ByVal inTaskNo As String, ByVal inFunctionNo As String, ByVal inMsgTitle As String, ByVal inMsgLevel As String, ByVal inMsgContent As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/queryNFCNotifierByFunc", ReplyAction:="http://tempuri.org/INfcService/queryNFCNotifierByFuncResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function queryNFCNotifierByFunc(ByRef columnName() As String, ByRef columnValue() As Object) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/saveNFCNotifierByFunc", ReplyAction:="http://tempuri.org/INfcService/saveNFCNotifierByFuncResponse")>  _
        Function saveNFCNotifierByFunc(ByVal inSaveData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/deleteNFCNotifierByFunc", ReplyAction:="http://tempuri.org/INfcService/deleteNFCNotifierByFuncResponse")>  _
        Function deleteNFCNotifierByFunc(ByVal inDeleteData As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/getNotifyMessageByDeploy", ReplyAction:="http://tempuri.org/INfcService/getNotifyMessageByDeployResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function getNotifyMessageByDeploy(ByRef columnName() As String, ByRef columnValue() As Object) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/QueryDeployByToDay", ReplyAction:="http://tempuri.org/INfcService/QueryDeployByToDayResponse")>  _
        Function QueryDeployByToDay(ByVal _type As String, ByVal user As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUIExternalRightNow", ReplyAction:="http://tempuri.org/INfcService/NotifyUIExternalRightNowResponse")>  _
        Sub NotifyUIExternalRightNow(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal external As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyMailWithEsrFormat", ReplyAction:="http://tempuri.org/INfcService/NotifyMailWithEsrFormatResponse")>  _
        Sub NotifyMailWithEsrFormat(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/NotifyUIWithStartAndEndTime", ReplyAction:="http://tempuri.org/INfcService/NotifyUIWithStartAndEndTimeResponse")>  _
        Sub NotifyUIWithStartAndEndTime(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal Start_Time As String, ByVal End_Time As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/reMarkRead", ReplyAction:="http://tempuri.org/INfcService/reMarkReadResponse")>  _
        Function reMarkRead(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/InsertNFCNotifyMsg", ReplyAction:="http://tempuri.org/INfcService/InsertNFCNotifyMsgResponse")>  _
        Function InsertNFCNotifyMsg(ByVal data As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/QueryNFCNotifyMsgByUserId", ReplyAction:="http://tempuri.org/INfcService/QueryNFCNotifyMsgByUserIdResponse")>  _
        Function QueryNFCNotifyMsgByUserId(ByVal UserId As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/QueryNFCNotifyMsgByCond", ReplyAction:="http://tempuri.org/INfcService/QueryNFCNotifyMsgByCondResponse")>  _
        Function QueryNFCNotifyMsgByCond(ByVal StartSendDate As String, ByVal EndSendDate As String, ByVal Fun_Function_No As String, ByVal Type As String, ByVal Level As String, ByVal Status As String, ByVal Recipient As String, ByVal sendUser As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/initialNfcQueryExportUI", ReplyAction:="http://tempuri.org/INfcService/initialNfcQueryExportUIResponse")>  _
        Function initialNfcQueryExportUI() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/insertGroupMember", ReplyAction:="http://tempuri.org/INfcService/insertGroupMemberResponse")>  _
        Function insertGroupMember(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/deleteGroupMember", ReplyAction:="http://tempuri.org/INfcService/deleteGroupMemberResponse")>  _
        Function deleteGroupMember(ByVal groupID As String, ByVal employeeCode As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/deleteGroupMembers", ReplyAction:="http://tempuri.org/INfcService/deleteGroupMembersResponse")>  _
        Function deleteGroupMembers(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/queryGroupMember", ReplyAction:="http://tempuri.org/INfcService/queryGroupMemberResponse")>  _
        Function queryGroupMember(ByVal GroupID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/queryGroupMember1", ReplyAction:="http://tempuri.org/INfcService/queryGroupMember1Response")>  _
        Function queryGroupMember1(ByVal GroupID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/UpdateIP", ReplyAction:="http://tempuri.org/INfcService/UpdateIPResponse")>  _
        Function UpdateIP(ByVal mid As String, ByVal call_IP As String, ByVal modified_User As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/UpdateSpecFlag", ReplyAction:="http://tempuri.org/INfcService/UpdateSpecFlagResponse")>  _
        Function UpdateSpecFlag(ByVal mid As String, ByVal modified_User As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/deleteSenderByGroupTxId", ReplyAction:="http://tempuri.org/INfcService/deleteSenderByGroupTxIdResponse")>  _
        Function deleteSenderByGroupTxId(ByRef Group_Tx_Id As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/updateSender", ReplyAction:="http://tempuri.org/INfcService/updateSenderResponse")>  _
        Function updateSender(ByRef ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/insertGroup", ReplyAction:="http://tempuri.org/INfcService/insertGroupResponse")>  _
        Function insertGroup(ByVal groupName As String, ByVal createUser As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/deleteGroup", ReplyAction:="http://tempuri.org/INfcService/deleteGroupResponse")>  _
        Function deleteGroup(ByVal groupID As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/queryGroupByUser", ReplyAction:="http://tempuri.org/INfcService/queryGroupByUserResponse")>  _
        Function queryGroupByUser(ByVal employee_Code As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/UpdateReplayMsg", ReplyAction:="http://tempuri.org/INfcService/UpdateReplayMsgResponse")>  _
        Function UpdateReplayMsg(ByVal MID As String, ByVal replayMsg As String, ByVal modifyUser As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/getNfcPhrase", ReplyAction:="http://tempuri.org/INfcService/getNfcPhraseResponse")>  _
        Function getNfcPhrase(ByVal ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/updateNfcNotifyMsgEndTime", ReplyAction:="http://tempuri.org/INfcService/updateNfcNotifyMsgEndTimeResponse")>  _
        Function updateNfcNotifyMsgEndTime(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/queryNfcNotifyMsgBySubject", ReplyAction:="http://tempuri.org/INfcService/queryNfcNotifyMsgBySubjectResponse")>  _
        Function queryNfcNotifyMsgBySubject(ByVal subject As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/QueryNFCNotifyMsg", ReplyAction:="http://tempuri.org/INfcService/QueryNFCNotifyMsgResponse")>  _
        Function QueryNFCNotifyMsg(ByVal MID As String, ByVal UserId As String, ByVal StartDate As String, ByVal EndDate As String, ByVal Status As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INfcService/UpdateNFCNotifyMsg", ReplyAction:="http://tempuri.org/INfcService/UpdateNFCNotifyMsgResponse")>  _
        Function UpdateNFCNotifyMsg(ByVal MID As String, ByVal ReplyMsg As String, ByVal Modified_User As String, ByVal Modified_Time As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface INfcServiceChannel
        Inherits NfcServiceReference.INfcService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NfcServiceClient
        Inherits System.ServiceModel.ClientBase(Of NfcServiceReference.INfcService)
        Implements NfcServiceReference.INfcService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function readUIMessage24HrAuto(ByVal empNO As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.readUIMessage24HrAuto
            Return MyBase.Channel.readUIMessage24HrAuto(empNO)
        End Function
        
        Public Function readUIMessage24Hr(ByVal empNO As String, ByVal depNo As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.readUIMessage24Hr
            Return MyBase.Channel.readUIMessage24Hr(empNO, depNo)
        End Function
        
        Public Function readUIMessageAuto(ByVal empNO As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.readUIMessageAuto
            Return MyBase.Channel.readUIMessageAuto(empNO)
        End Function
        
        Public Function readUIMessage(ByVal empNO As String, ByVal depNo As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.readUIMessage
            Return MyBase.Channel.readUIMessage(empNO, depNo)
        End Function
        
        Public Sub NotifyAllUI(ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyAllUI
            MyBase.Channel.NotifyAllUI(subject, msg, startTime, endTime, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyAllUIExternal(ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyAllUIExternal
            MyBase.Channel.NotifyAllUIExternal(subject, msg, startTime, endTime, external, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyDepUI(ByVal empDept As String, ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyDepUI
            MyBase.Channel.NotifyDepUI(empDept, subject, msg, startTime, endTime, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyDepUIExternal(ByVal empDept As String, ByVal subject As String, ByVal msg As String, ByVal startTime As Date, ByVal endTime As Date, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyDepUIExternal
            MyBase.Channel.NotifyDepUIExternal(empDept, subject, msg, startTime, endTime, external, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyUIMulti(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyUIMulti
            MyBase.Channel.NotifyUIMulti(drEmpNo, subject, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyUIMultiExternal(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal external As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyUIMultiExternal
            MyBase.Channel.NotifyUIMultiExternal(drEmpNo, subject, msg, external, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyUI(ByVal drEmpNo As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyUI
            MyBase.Channel.NotifyUI(drEmpNo, subject, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyUIExternal(ByVal drEmpNo As String, ByVal subject As String, ByVal msg As String, ByVal external As String) Implements NfcServiceReference.INfcService.NotifyUIExternal
            MyBase.Channel.NotifyUIExternal(drEmpNo, subject, msg, external)
        End Sub
        
        Public Sub NotifyMailMulti(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String) Implements NfcServiceReference.INfcService.NotifyMailMulti
            MyBase.Channel.NotifyMailMulti(EmpMail, subject, msg)
        End Sub
        
        Public Sub NotifyMailMultiReply(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String) Implements NfcServiceReference.INfcService.NotifyMailMultiReply
            MyBase.Channel.NotifyMailMultiReply(EmpMail, subject, msg, replymsg)
        End Sub
        
        Public Sub NotifyMail(ByVal EmpMail As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyMail
            MyBase.Channel.NotifyMail(EmpMail, subject, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifyMailReply(ByVal EmpMail As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifyMailReply
            MyBase.Channel.NotifyMailReply(EmpMail, subject, msg, replymsg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifySMS(ByVal drEmpNo As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifySMS
            MyBase.Channel.NotifySMS(drEmpNo, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifySMSMulti(ByVal drEmpNo() As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String) Implements NfcServiceReference.INfcService.NotifySMSMulti
            MyBase.Channel.NotifySMSMulti(drEmpNo, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No)
        End Sub
        
        Public Sub NotifySMSMultiWithSubject(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String) Implements NfcServiceReference.INfcService.NotifySMSMultiWithSubject
            MyBase.Channel.NotifySMSMultiWithSubject(drEmpNo, subject, msg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No, CreateUser, SpecFlag)
        End Sub
        
        Public Sub NotifyByFunctionNo(ByVal inSystemNo As String, ByVal inSubSystemNo As String, ByVal inTaskNo As String, ByVal inFunctionNo As String, ByVal inMsgTitle As String, ByVal inMsgLevel As String, ByVal inMsgContent As String) Implements NfcServiceReference.INfcService.NotifyByFunctionNo
            MyBase.Channel.NotifyByFunctionNo(inSystemNo, inSubSystemNo, inTaskNo, inFunctionNo, inMsgTitle, inMsgLevel, inMsgContent)
        End Sub
        
        Public Function queryNFCNotifierByFunc(ByRef columnName() As String, ByRef columnValue() As Object) As System.Data.DataSet Implements NfcServiceReference.INfcService.queryNFCNotifierByFunc
            Return MyBase.Channel.queryNFCNotifierByFunc(columnName, columnValue)
        End Function
        
        Public Function saveNFCNotifierByFunc(ByVal inSaveData As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.saveNFCNotifierByFunc
            Return MyBase.Channel.saveNFCNotifierByFunc(inSaveData)
        End Function
        
        Public Function deleteNFCNotifierByFunc(ByVal inDeleteData As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.deleteNFCNotifierByFunc
            Return MyBase.Channel.deleteNFCNotifierByFunc(inDeleteData)
        End Function
        
        Public Function getNotifyMessageByDeploy(ByRef columnName() As String, ByRef columnValue() As Object) As System.Data.DataSet Implements NfcServiceReference.INfcService.getNotifyMessageByDeploy
            Return MyBase.Channel.getNotifyMessageByDeploy(columnName, columnValue)
        End Function
        
        Public Function QueryDeployByToDay(ByVal _type As String, ByVal user As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.QueryDeployByToDay
            Return MyBase.Channel.QueryDeployByToDay(_type, user)
        End Function
        
        Public Sub NotifyUIExternalRightNow(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal external As String) Implements NfcServiceReference.INfcService.NotifyUIExternalRightNow
            MyBase.Channel.NotifyUIExternalRightNow(drEmpNo, subject, msg, external)
        End Sub
        
        Public Sub NotifyMailWithEsrFormat(ByVal EmpMail() As String, ByVal subject As String, ByVal msg As String, ByVal replymsg As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String) Implements NfcServiceReference.INfcService.NotifyMailWithEsrFormat
            MyBase.Channel.NotifyMailWithEsrFormat(EmpMail, subject, msg, replymsg, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No, CreateUser, SpecFlag)
        End Sub
        
        Public Sub NotifyUIWithStartAndEndTime(ByVal drEmpNo() As String, ByVal subject As String, ByVal msg As String, ByVal Start_Time As String, ByVal End_Time As String, ByVal App_System_No As String, ByVal Sub_System_No As String, ByVal Tsk_Task_no As String, ByVal Fun_Function_No As String, ByVal CreateUser As String, ByVal SpecFlag As String) Implements NfcServiceReference.INfcService.NotifyUIWithStartAndEndTime
            MyBase.Channel.NotifyUIWithStartAndEndTime(drEmpNo, subject, msg, Start_Time, End_Time, App_System_No, Sub_System_No, Tsk_Task_no, Fun_Function_No, CreateUser, SpecFlag)
        End Sub
        
        Public Function reMarkRead(ByVal ds As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.reMarkRead
            Return MyBase.Channel.reMarkRead(ds)
        End Function
        
        Public Function InsertNFCNotifyMsg(ByVal data As System.Data.DataSet) As String Implements NfcServiceReference.INfcService.InsertNFCNotifyMsg
            Return MyBase.Channel.InsertNFCNotifyMsg(data)
        End Function
        
        Public Function QueryNFCNotifyMsgByUserId(ByVal UserId As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.QueryNFCNotifyMsgByUserId
            Return MyBase.Channel.QueryNFCNotifyMsgByUserId(UserId)
        End Function
        
        Public Function QueryNFCNotifyMsgByCond(ByVal StartSendDate As String, ByVal EndSendDate As String, ByVal Fun_Function_No As String, ByVal Type As String, ByVal Level As String, ByVal Status As String, ByVal Recipient As String, ByVal sendUser As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.QueryNFCNotifyMsgByCond
            Return MyBase.Channel.QueryNFCNotifyMsgByCond(StartSendDate, EndSendDate, Fun_Function_No, Type, Level, Status, Recipient, sendUser)
        End Function
        
        Public Function initialNfcQueryExportUI() As System.Data.DataSet Implements NfcServiceReference.INfcService.initialNfcQueryExportUI
            Return MyBase.Channel.initialNfcQueryExportUI
        End Function
        
        Public Function insertGroupMember(ByVal ds As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.insertGroupMember
            Return MyBase.Channel.insertGroupMember(ds)
        End Function
        
        Public Function deleteGroupMember(ByVal groupID As String, ByVal employeeCode As String) As Integer Implements NfcServiceReference.INfcService.deleteGroupMember
            Return MyBase.Channel.deleteGroupMember(groupID, employeeCode)
        End Function
        
        Public Function deleteGroupMembers(ByVal ds As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.deleteGroupMembers
            Return MyBase.Channel.deleteGroupMembers(ds)
        End Function
        
        Public Function queryGroupMember(ByVal GroupID As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.queryGroupMember
            Return MyBase.Channel.queryGroupMember(GroupID)
        End Function
        
        Public Function queryGroupMember1(ByVal GroupID As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.queryGroupMember1
            Return MyBase.Channel.queryGroupMember1(GroupID)
        End Function
        
        Public Function UpdateIP(ByVal mid As String, ByVal call_IP As String, ByVal modified_User As String) As Integer Implements NfcServiceReference.INfcService.UpdateIP
            Return MyBase.Channel.UpdateIP(mid, call_IP, modified_User)
        End Function
        
        Public Function UpdateSpecFlag(ByVal mid As String, ByVal modified_User As String) As Integer Implements NfcServiceReference.INfcService.UpdateSpecFlag
            Return MyBase.Channel.UpdateSpecFlag(mid, modified_User)
        End Function
        
        Public Function deleteSenderByGroupTxId(ByRef Group_Tx_Id As String) As Integer Implements NfcServiceReference.INfcService.deleteSenderByGroupTxId
            Return MyBase.Channel.deleteSenderByGroupTxId(Group_Tx_Id)
        End Function
        
        Public Function updateSender(ByRef ds As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.updateSender
            Return MyBase.Channel.updateSender(ds)
        End Function
        
        Public Function insertGroup(ByVal groupName As String, ByVal createUser As String) As Integer Implements NfcServiceReference.INfcService.insertGroup
            Return MyBase.Channel.insertGroup(groupName, createUser)
        End Function
        
        Public Function deleteGroup(ByVal groupID As String) As Integer Implements NfcServiceReference.INfcService.deleteGroup
            Return MyBase.Channel.deleteGroup(groupID)
        End Function
        
        Public Function queryGroupByUser(ByVal employee_Code As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.queryGroupByUser
            Return MyBase.Channel.queryGroupByUser(employee_Code)
        End Function
        
        Public Function UpdateReplayMsg(ByVal MID As String, ByVal replayMsg As String, ByVal modifyUser As String) As Integer Implements NfcServiceReference.INfcService.UpdateReplayMsg
            Return MyBase.Channel.UpdateReplayMsg(MID, replayMsg, modifyUser)
        End Function
        
        Public Function getNfcPhrase(ByVal ID As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.getNfcPhrase
            Return MyBase.Channel.getNfcPhrase(ID)
        End Function
        
        Public Function updateNfcNotifyMsgEndTime(ByVal ds As System.Data.DataSet) As Integer Implements NfcServiceReference.INfcService.updateNfcNotifyMsgEndTime
            Return MyBase.Channel.updateNfcNotifyMsgEndTime(ds)
        End Function
        
        Public Function queryNfcNotifyMsgBySubject(ByVal subject As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.queryNfcNotifyMsgBySubject
            Return MyBase.Channel.queryNfcNotifyMsgBySubject(subject)
        End Function
        
        Public Function QueryNFCNotifyMsg(ByVal MID As String, ByVal UserId As String, ByVal StartDate As String, ByVal EndDate As String, ByVal Status As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.QueryNFCNotifyMsg
            Return MyBase.Channel.QueryNFCNotifyMsg(MID, UserId, StartDate, EndDate, Status)
        End Function
        
        Public Function UpdateNFCNotifyMsg(ByVal MID As String, ByVal ReplyMsg As String, ByVal Modified_User As String, ByVal Modified_Time As String) As System.Data.DataSet Implements NfcServiceReference.INfcService.UpdateNFCNotifyMsg
            Return MyBase.Channel.UpdateNFCNotifyMsg(MID, ReplyMsg, Modified_User, Modified_Time)
        End Function
    End Class
End Namespace
