'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IccServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IccServiceReference.IIccService")>  _
    Public Interface IIccService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1queryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1queryByPKResponse")>  _
        Function ICCInteractVerify1queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1queryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1queryAllYNShowResponse")>  _
        Function ICCInteractVerify1queryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1queryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1queryByPKYNShowResponse")>  _
        Function ICCInteractVerify1queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1insert", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1insertResponse")>  _
        Function ICCInteractVerify1insert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1update", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1updateResponse")>  _
        Function ICCInteractVerify1update(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1queryAll", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1queryAllResponse")>  _
        Function ICCInteractVerify1queryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2delete", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2deleteResponse")>  _
        Function ICCInteractVerify2delete(ByRef pk_Serial_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2queryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2queryByPKResponse")>  _
        Function ICCInteractVerify2queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2queryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2queryAllYNShowResponse")>  _
        Function ICCInteractVerify2queryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2queryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2queryByPKYNShowResponse")>  _
        Function ICCInteractVerify2queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2insert", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2insertResponse")>  _
        Function ICCInteractVerify2insert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2update", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2updateResponse")>  _
        Function ICCInteractVerify2update(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify2queryAll", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify2queryAllResponse")>  _
        Function ICCInteractVerify2queryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify3delete", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify3deleteResponse")>  _
        Function ICCInteractVerify3delete(ByRef pk_Serial_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify3queryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify3queryByPKResponse")>  _
        Function ICCInteractVerify3queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify3insert", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify3insertResponse")>  _
        Function ICCInteractVerify3insert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify3update", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify3updateResponse")>  _
        Function ICCInteractVerify3update(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify3queryAll", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify3queryAllResponse")>  _
        Function ICCInteractVerify3queryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4delete", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4deleteResponse")>  _
        Function ICCInteractVerify4delete(ByRef pk_Serial_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4queryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4queryByPKResponse")>  _
        Function ICCInteractVerify4queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4queryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4queryAllYNShowResponse")>  _
        Function ICCInteractVerify4queryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4queryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4queryByPKYNShowResponse")>  _
        Function ICCInteractVerify4queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4insert", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4insertResponse")>  _
        Function ICCInteractVerify4insert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4update", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4updateResponse")>  _
        Function ICCInteractVerify4update(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify4queryAll", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify4queryAllResponse")>  _
        Function ICCInteractVerify4queryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCUploadDataMaintainBSCancelData", ReplyAction:="http://tempuri.org/IIccService/ICCUploadDataMaintainBSCancelDataResponse")>  _
        Function ICCUploadDataMaintainBSCancelData(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/GetIcdName", ReplyAction:="http://tempuri.org/IIccService/GetIcdNameResponse")>  _
        Function GetIcdName(ByVal IcdCode As String, ByVal IsGetEngName As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/GetHospName", ReplyAction:="http://tempuri.org/IIccService/GetHospNameResponse")>  _
        Function GetHospName(ByVal HospCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/GetTreatmentName", ReplyAction:="http://tempuri.org/IIccService/GetTreatmentNameResponse")>  _
        Function GetTreatmentName(ByVal TreatmentCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ProcessPatientOrganDonate", ReplyAction:="http://tempuri.org/IIccService/ProcessPatientOrganDonateResponse")>  _
        Function ProcessPatientOrganDonate(ByVal ChartNo As String, ByVal DNRKindId As String, ByVal LoginUser As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetRegisterBasic", ReplyAction:="http://tempuri.org/IIccService/queryGetRegisterBasicResponse")>  _
        Function queryGetRegisterBasic(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetRegisterBasic", ReplyAction:="http://tempuri.org/IIccService/updateGetRegisterBasicResponse")>  _
        Function updateGetRegisterBasic(ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetRegisterBasic", ReplyAction:="http://tempuri.org/IIccService/insertGetRegisterBasicResponse")>  _
        Function insertGetRegisterBasic(ByVal retValue As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/deleteWriteNewBorn", ReplyAction:="http://tempuri.org/IIccService/deleteWriteNewBornResponse")>  _
        Function deleteWriteNewBorn(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/deleteUpdateICCard", ReplyAction:="http://tempuri.org/IIccService/deleteUpdateICCardResponse")>  _
        Function deleteUpdateICCard(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/deleteUnGetSeqNumber", ReplyAction:="http://tempuri.org/IIccService/deleteUnGetSeqNumberResponse")>  _
        Function deleteUnGetSeqNumber(ByVal pk_Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetLastSeqNum", ReplyAction:="http://tempuri.org/IIccService/queryGetLastSeqNumResponse")>  _
        Function queryGetLastSeqNum(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetLastSeqNum", ReplyAction:="http://tempuri.org/IIccService/updateGetLastSeqNumResponse")>  _
        Function updateGetLastSeqNum(ByVal Card_Sn As String, ByVal retLastSeqNum As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetLastSeqNum", ReplyAction:="http://tempuri.org/IIccService/insertGetLastSeqNumResponse")>  _
        Function insertGetLastSeqNum(ByVal Card_Sn As String, ByVal retLastSeqNum As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetCriticalIllness", ReplyAction:="http://tempuri.org/IIccService/queryGetCriticalIllnessResponse")>  _
        Function queryGetCriticalIllness(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetCriticalIllness", ReplyAction:="http://tempuri.org/IIccService/updateGetCriticalIllnessResponse")>  _
        Function updateGetCriticalIllness(ByVal Card_Sn As String, ByVal retRetain As String, ByVal rethospitalMark As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetCriticalIllness", ReplyAction:="http://tempuri.org/IIccService/insertGetCriticalIllnessResponse")>  _
        Function insertGetCriticalIllness(ByVal Card_Sn As String, ByVal retRetain As String, ByVal rethospitalMark As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetTreatmentNoNeedHPC", ReplyAction:="http://tempuri.org/IIccService/queryGetTreatmentNoNeedHPCResponse")>  _
        Function queryGetTreatmentNoNeedHPC(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetTreatmentNoNeedHPC", ReplyAction:="http://tempuri.org/IIccService/updateGetTreatmentNoNeedHPCResponse")>  _
        Function updateGetTreatmentNoNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/deleteGetTreatmentNoNeedHPC", ReplyAction:="http://tempuri.org/IIccService/deleteGetTreatmentNoNeedHPCResponse")>  _
        Function deleteGetTreatmentNoNeedHPC(ByVal Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetTreatmentNoNeedHPC", ReplyAction:="http://tempuri.org/IIccService/insertGetTreatmentNoNeedHPCResponse")>  _
        Function insertGetTreatmentNoNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetTreatmentNeedHPC", ReplyAction:="http://tempuri.org/IIccService/queryGetTreatmentNeedHPCResponse")>  _
        Function queryGetTreatmentNeedHPC(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetTreatmentNeedHPC", ReplyAction:="http://tempuri.org/IIccService/updateGetTreatmentNeedHPCResponse")>  _
        Function updateGetTreatmentNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/deleteGetTreatmentNeedHPC", ReplyAction:="http://tempuri.org/IIccService/deleteGetTreatmentNeedHPCResponse")>  _
        Function deleteGetTreatmentNeedHPC(ByVal Card_Sn As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetTreatmentNeedHPC", ReplyAction:="http://tempuri.org/IIccService/insertGetTreatmentNeedHPCResponse")>  _
        Function insertGetTreatmentNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetRegisterPrevent", ReplyAction:="http://tempuri.org/IIccService/queryGetRegisterPreventResponse")>  _
        Function queryGetRegisterPrevent(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetRegisterPrevent", ReplyAction:="http://tempuri.org/IIccService/updateGetRegisterPreventResponse")>  _
        Function updateGetRegisterPrevent(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetRegisterPrevent", ReplyAction:="http://tempuri.org/IIccService/insertGetRegisterPreventResponse")>  _
        Function insertGetRegisterPrevent(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetRegisterPregnant", ReplyAction:="http://tempuri.org/IIccService/queryGetRegisterPregnantResponse")>  _
        Function queryGetRegisterPregnant(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetRegisterPregnant", ReplyAction:="http://tempuri.org/IIccService/updateGetRegisterPregnantResponse")>  _
        Function updateGetRegisterPregnant(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetRegisterPregnant", ReplyAction:="http://tempuri.org/IIccService/insertGetRegisterPregnantResponse")>  _
        Function insertGetRegisterPregnant(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryReadPrescriptMain", ReplyAction:="http://tempuri.org/IIccService/queryReadPrescriptMainResponse")>  _
        Function queryReadPrescriptMain(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateReadPrescriptMain", ReplyAction:="http://tempuri.org/IIccService/updateReadPrescriptMainResponse")>  _
        Function updateReadPrescriptMain(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertReadPrescriptMain", ReplyAction:="http://tempuri.org/IIccService/insertReadPrescriptMainResponse")>  _
        Function insertReadPrescriptMain(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryReadPrescriptLongTerm", ReplyAction:="http://tempuri.org/IIccService/queryReadPrescriptLongTermResponse")>  _
        Function queryReadPrescriptLongTerm(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateReadPrescriptLongTerm", ReplyAction:="http://tempuri.org/IIccService/updateReadPrescriptLongTermResponse")>  _
        Function updateReadPrescriptLongTerm(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertReadPrescriptLongTerm", ReplyAction:="http://tempuri.org/IIccService/insertReadPrescriptLongTermResponse")>  _
        Function insertReadPrescriptLongTerm(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryReadPrescriptHVE", ReplyAction:="http://tempuri.org/IIccService/queryReadPrescriptHVEResponse")>  _
        Function queryReadPrescriptHVE(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateReadPrescriptHVE", ReplyAction:="http://tempuri.org/IIccService/updateReadPrescriptHVEResponse")>  _
        Function updateReadPrescriptHVE(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertReadPrescriptHVE", ReplyAction:="http://tempuri.org/IIccService/insertReadPrescriptHVEResponse")>  _
        Function insertReadPrescriptHVE(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryReadPrescriptAllergic", ReplyAction:="http://tempuri.org/IIccService/queryReadPrescriptAllergicResponse")>  _
        Function queryReadPrescriptAllergic(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateReadPrescriptAllergic", ReplyAction:="http://tempuri.org/IIccService/updateReadPrescriptAllergicResponse")>  _
        Function updateReadPrescriptAllergic(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertReadPrescriptAllergic", ReplyAction:="http://tempuri.org/IIccService/insertReadPrescriptAllergicResponse")>  _
        Function insertReadPrescriptAllergic(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetInoculateData", ReplyAction:="http://tempuri.org/IIccService/queryGetInoculateDataResponse")>  _
        Function queryGetInoculateData(ByVal Card_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateGetInoculateData", ReplyAction:="http://tempuri.org/IIccService/updateGetInoculateDataResponse")>  _
        Function updateGetInoculateData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertGetInoculateData", ReplyAction:="http://tempuri.org/IIccService/insertGetInoculateDataResponse")>  _
        Function insertGetInoculateData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertInsertHealth", ReplyAction:="http://tempuri.org/IIccService/insertInsertHealthResponse")>  _
        Function insertInsertHealth(ByVal seqNumber As String, ByVal uploadType As String, ByVal sourceType1 As String, ByVal srcSeq As String, ByVal medicalRecNo As String, ByVal mb1Value As System.Data.DataSet, ByVal mb2ValueList As System.Data.DataSet, ByVal createUser As String, ByVal createTime As Date, ByVal errorCodeMessage As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/insertInsertInoculate", ReplyAction:="http://tempuri.org/IIccService/insertInsertInoculateResponse")>  _
        Function insertInsertInoculate(ByVal seqNumber As String, ByVal uploadType As String, ByVal sourceType1 As String, ByVal srcSeq As String, ByVal medicalRecNo As String, ByVal fBabyStool As Boolean, ByVal mb1Value As System.Data.DataSet, ByVal mb2ValueList As System.Data.DataSet, ByVal createUser As String, ByVal createTime As Date, ByVal treatmentTime As Date) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryGetMustUploadField", ReplyAction:="http://tempuri.org/IIccService/queryGetMustUploadFieldResponse")>  _
        Function queryGetMustUploadField(ByVal treatmentCategoryId As String, ByVal dataType As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryUpload", ReplyAction:="http://tempuri.org/IIccService/queryUploadResponse")>  _
        Function queryUpload(ByVal healthSnListStr As String, ByVal inoculationSnListStr As String, ByVal uploadTypeId As String, ByVal fBatch As Boolean, ByVal user As String, ByVal Config_Name_Path As String, ByVal Config_Name_Mail As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateUpload", ReplyAction:="http://tempuri.org/IIccService/updateUploadResponse")>  _
        Function updateUpload(ByVal ds As System.Data.DataSet, ByVal user As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/updateUpload2", ReplyAction:="http://tempuri.org/IIccService/updateUpload2Response")>  _
        Function updateUpload2(ByVal ds As System.Data.DataSet, ByVal UPLOAD_DATE As String, ByVal user As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryMust_Field_Verify", ReplyAction:="http://tempuri.org/IIccService/queryMust_Field_VerifyResponse")>  _
        Function queryMust_Field_Verify(ByVal mb1ValueA01 As String, ByVal mb1ValueA23 As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryField_Length_Verify", ReplyAction:="http://tempuri.org/IIccService/queryField_Length_VerifyResponse")>  _
        Function queryField_Length_Verify(ByVal totalID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/querySelf_Verify", ReplyAction:="http://tempuri.org/IIccService/querySelf_VerifyResponse")>  _
        Function querySelf_Verify(ByVal totalID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryInteract_Verify1", ReplyAction:="http://tempuri.org/IIccService/queryInteract_Verify1Response")>  _
        Function queryInteract_Verify1() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryInteract_Verify2", ReplyAction:="http://tempuri.org/IIccService/queryInteract_Verify2Response")>  _
        Function queryInteract_Verify2() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryInteract_Verify3", ReplyAction:="http://tempuri.org/IIccService/queryInteract_Verify3Response")>  _
        Function queryInteract_Verify3() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryInteract_Verify4", ReplyAction:="http://tempuri.org/IIccService/queryInteract_Verify4Response")>  _
        Function queryInteract_Verify4() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/queryOnlineCheck", ReplyAction:="http://tempuri.org/IIccService/queryOnlineCheckResponse")>  _
        Function queryOnlineCheck(ByVal ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCCloudDrugPatientQueryCountByChartNo", ReplyAction:="http://tempuri.org/IIccService/ICCCloudDrugPatientQueryCountByChartNoResponse")>  _
        Function ICCCloudDrugPatientQueryCountByChartNo(ByVal chartNo As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCCloudDrugPatientQueryEffectivePatient", ReplyAction:="http://tempuri.org/IIccService/ICCCloudDrugPatientQueryEffectivePatientResponse")>  _
        Function ICCCloudDrugPatientQueryEffectivePatient() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCCloudDrugsQueryAssignColumnsByIdNo", ReplyAction:="http://tempuri.org/IIccService/ICCCloudDrugsQueryAssignColumnsByIdNoResponse")>  _
        Function ICCCloudDrugsQueryAssignColumnsByIdNo(ByVal idNo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifydeleteByPk", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifydeleteByPkResponse")>  _
        Function ICCMustFieldVerifydeleteByPk(ByVal pkCode As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyinsert", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyinsertResponse")>  _
        Function ICCMustFieldVerifyinsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyupdate", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyupdateResponse")>  _
        Function ICCMustFieldVerifyupdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryAll", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryAllResponse")>  _
        Function ICCMustFieldVerifyqueryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryByPKResponse")>  _
        Function ICCMustFieldVerifyqueryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryByPKYNShowResponse")>  _
        Function ICCMustFieldVerifyqueryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCMustFieldVerifyqueryAllYNShowResponse")>  _
        Function ICCMustFieldVerifyqueryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCFieldLengthVerifydelete", ReplyAction:="http://tempuri.org/IIccService/ICCFieldLengthVerifydeleteResponse")>  _
        Function ICCFieldLengthVerifydelete(ByVal pkCode As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCFieldLengthVerifyqueryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCFieldLengthVerifyqueryByPKResponse")>  _
        Function ICCFieldLengthVerifyqueryByPK(ByRef pk_ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCFieldLengthVerifyinsert", ReplyAction:="http://tempuri.org/IIccService/ICCFieldLengthVerifyinsertResponse")>  _
        Function ICCFieldLengthVerifyinsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCFieldLengthVerifyupdate", ReplyAction:="http://tempuri.org/IIccService/ICCFieldLengthVerifyupdateResponse")>  _
        Function ICCFieldLengthVerifyupdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCFieldLengthVerifyqueryAll", ReplyAction:="http://tempuri.org/IIccService/ICCFieldLengthVerifyqueryAllResponse")>  _
        Function ICCFieldLengthVerifyqueryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckdelete", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckdeleteResponse")>  _
        Function ICCOnlineCheckdelete(ByVal pk_ID As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckqueryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckqueryByPKResponse")>  _
        Function ICCOnlineCheckqueryByPK(ByRef pk_ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckqueryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckqueryAllYNShowResponse")>  _
        Function ICCOnlineCheckqueryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckqueryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckqueryByPKYNShowResponse")>  _
        Function ICCOnlineCheckqueryByPKYNShow(ByRef pk_ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckinsert", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckinsertResponse")>  _
        Function ICCOnlineCheckinsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckupdate", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckupdateResponse")>  _
        Function ICCOnlineCheckupdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCOnlineCheckqueryAll", ReplyAction:="http://tempuri.org/IIccService/ICCOnlineCheckqueryAllResponse")>  _
        Function ICCOnlineCheckqueryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifydelete", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifydeleteResponse")>  _
        Function ICCSelfVerifydelete(ByVal pk_ID As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyqueryByPK", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyqueryByPKResponse")>  _
        Function ICCSelfVerifyqueryByPK(ByRef pk_ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyqueryAllYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyqueryAllYNShowResponse")>  _
        Function ICCSelfVerifyqueryAllYNShow() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyqueryByPKYNShow", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyqueryByPKYNShowResponse")>  _
        Function ICCSelfVerifyqueryByPKYNShow(ByRef pk_ID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyinsert", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyinsertResponse")>  _
        Function ICCSelfVerifyinsert(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyupdate", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyupdateResponse")>  _
        Function ICCSelfVerifyupdate(ByVal ds As System.Data.DataSet) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCSelfVerifyqueryAll", ReplyAction:="http://tempuri.org/IIccService/ICCSelfVerifyqueryAllResponse")>  _
        Function ICCSelfVerifyqueryAll() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIccService/ICCInteractVerify1delete", ReplyAction:="http://tempuri.org/IIccService/ICCInteractVerify1deleteResponse")>  _
        Function ICCInteractVerify1delete(ByRef pk_Serial_Sn As String) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IIccServiceChannel
        Inherits IccServiceReference.IIccService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IccServiceClient
        Inherits System.ServiceModel.ClientBase(Of IccServiceReference.IIccService)
        Implements IccServiceReference.IIccService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ICCInteractVerify1queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify1queryByPK
            Return MyBase.Channel.ICCInteractVerify1queryByPK(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify1queryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify1queryAllYNShow
            Return MyBase.Channel.ICCInteractVerify1queryAllYNShow
        End Function
        
        Public Function ICCInteractVerify1queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify1queryByPKYNShow
            Return MyBase.Channel.ICCInteractVerify1queryByPKYNShow(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify1insert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify1insert
            Return MyBase.Channel.ICCInteractVerify1insert(ds)
        End Function
        
        Public Function ICCInteractVerify1update(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify1update
            Return MyBase.Channel.ICCInteractVerify1update(ds)
        End Function
        
        Public Function ICCInteractVerify1queryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify1queryAll
            Return MyBase.Channel.ICCInteractVerify1queryAll
        End Function
        
        Public Function ICCInteractVerify2delete(ByRef pk_Serial_Sn As String) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify2delete
            Return MyBase.Channel.ICCInteractVerify2delete(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify2queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify2queryByPK
            Return MyBase.Channel.ICCInteractVerify2queryByPK(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify2queryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify2queryAllYNShow
            Return MyBase.Channel.ICCInteractVerify2queryAllYNShow
        End Function
        
        Public Function ICCInteractVerify2queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify2queryByPKYNShow
            Return MyBase.Channel.ICCInteractVerify2queryByPKYNShow(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify2insert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify2insert
            Return MyBase.Channel.ICCInteractVerify2insert(ds)
        End Function
        
        Public Function ICCInteractVerify2update(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify2update
            Return MyBase.Channel.ICCInteractVerify2update(ds)
        End Function
        
        Public Function ICCInteractVerify2queryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify2queryAll
            Return MyBase.Channel.ICCInteractVerify2queryAll
        End Function
        
        Public Function ICCInteractVerify3delete(ByRef pk_Serial_Sn As String) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify3delete
            Return MyBase.Channel.ICCInteractVerify3delete(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify3queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify3queryByPK
            Return MyBase.Channel.ICCInteractVerify3queryByPK(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify3insert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify3insert
            Return MyBase.Channel.ICCInteractVerify3insert(ds)
        End Function
        
        Public Function ICCInteractVerify3update(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify3update
            Return MyBase.Channel.ICCInteractVerify3update(ds)
        End Function
        
        Public Function ICCInteractVerify3queryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify3queryAll
            Return MyBase.Channel.ICCInteractVerify3queryAll
        End Function
        
        Public Function ICCInteractVerify4delete(ByRef pk_Serial_Sn As String) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify4delete
            Return MyBase.Channel.ICCInteractVerify4delete(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify4queryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify4queryByPK
            Return MyBase.Channel.ICCInteractVerify4queryByPK(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify4queryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify4queryAllYNShow
            Return MyBase.Channel.ICCInteractVerify4queryAllYNShow
        End Function
        
        Public Function ICCInteractVerify4queryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify4queryByPKYNShow
            Return MyBase.Channel.ICCInteractVerify4queryByPKYNShow(pk_Serial_Sn)
        End Function
        
        Public Function ICCInteractVerify4insert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify4insert
            Return MyBase.Channel.ICCInteractVerify4insert(ds)
        End Function
        
        Public Function ICCInteractVerify4update(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify4update
            Return MyBase.Channel.ICCInteractVerify4update(ds)
        End Function
        
        Public Function ICCInteractVerify4queryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCInteractVerify4queryAll
            Return MyBase.Channel.ICCInteractVerify4queryAll
        End Function
        
        Public Function ICCUploadDataMaintainBSCancelData(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCUploadDataMaintainBSCancelData
            Return MyBase.Channel.ICCUploadDataMaintainBSCancelData(ds)
        End Function
        
        Public Function GetIcdName(ByVal IcdCode As String, ByVal IsGetEngName As Boolean) As String Implements IccServiceReference.IIccService.GetIcdName
            Return MyBase.Channel.GetIcdName(IcdCode, IsGetEngName)
        End Function
        
        Public Function GetHospName(ByVal HospCode As String) As String Implements IccServiceReference.IIccService.GetHospName
            Return MyBase.Channel.GetHospName(HospCode)
        End Function
        
        Public Function GetTreatmentName(ByVal TreatmentCode As String) As String Implements IccServiceReference.IIccService.GetTreatmentName
            Return MyBase.Channel.GetTreatmentName(TreatmentCode)
        End Function
        
        Public Function ProcessPatientOrganDonate(ByVal ChartNo As String, ByVal DNRKindId As String, ByVal LoginUser As String) As Integer Implements IccServiceReference.IIccService.ProcessPatientOrganDonate
            Return MyBase.Channel.ProcessPatientOrganDonate(ChartNo, DNRKindId, LoginUser)
        End Function
        
        Public Function queryGetRegisterBasic(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetRegisterBasic
            Return MyBase.Channel.queryGetRegisterBasic(Card_Sn)
        End Function
        
        Public Function updateGetRegisterBasic(ByVal retValue As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetRegisterBasic
            Return MyBase.Channel.updateGetRegisterBasic(retValue)
        End Function
        
        Public Function insertGetRegisterBasic(ByVal retValue As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetRegisterBasic
            Return MyBase.Channel.insertGetRegisterBasic(retValue)
        End Function
        
        Public Function deleteWriteNewBorn(ByVal pk_Card_Sn As String) As Integer Implements IccServiceReference.IIccService.deleteWriteNewBorn
            Return MyBase.Channel.deleteWriteNewBorn(pk_Card_Sn)
        End Function
        
        Public Function deleteUpdateICCard(ByVal pk_Card_Sn As String) As Integer Implements IccServiceReference.IIccService.deleteUpdateICCard
            Return MyBase.Channel.deleteUpdateICCard(pk_Card_Sn)
        End Function
        
        Public Function deleteUnGetSeqNumber(ByVal pk_Card_Sn As String) As Integer Implements IccServiceReference.IIccService.deleteUnGetSeqNumber
            Return MyBase.Channel.deleteUnGetSeqNumber(pk_Card_Sn)
        End Function
        
        Public Function queryGetLastSeqNum(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetLastSeqNum
            Return MyBase.Channel.queryGetLastSeqNum(Card_Sn)
        End Function
        
        Public Function updateGetLastSeqNum(ByVal Card_Sn As String, ByVal retLastSeqNum As String) As Integer Implements IccServiceReference.IIccService.updateGetLastSeqNum
            Return MyBase.Channel.updateGetLastSeqNum(Card_Sn, retLastSeqNum)
        End Function
        
        Public Function insertGetLastSeqNum(ByVal Card_Sn As String, ByVal retLastSeqNum As String) As Integer Implements IccServiceReference.IIccService.insertGetLastSeqNum
            Return MyBase.Channel.insertGetLastSeqNum(Card_Sn, retLastSeqNum)
        End Function
        
        Public Function queryGetCriticalIllness(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetCriticalIllness
            Return MyBase.Channel.queryGetCriticalIllness(Card_Sn)
        End Function
        
        Public Function updateGetCriticalIllness(ByVal Card_Sn As String, ByVal retRetain As String, ByVal rethospitalMark As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetCriticalIllness
            Return MyBase.Channel.updateGetCriticalIllness(Card_Sn, retRetain, rethospitalMark, retValueList)
        End Function
        
        Public Function insertGetCriticalIllness(ByVal Card_Sn As String, ByVal retRetain As String, ByVal rethospitalMark As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetCriticalIllness
            Return MyBase.Channel.insertGetCriticalIllness(Card_Sn, retRetain, rethospitalMark, retValueList)
        End Function
        
        Public Function queryGetTreatmentNoNeedHPC(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetTreatmentNoNeedHPC
            Return MyBase.Channel.queryGetTreatmentNoNeedHPC(Card_Sn)
        End Function
        
        Public Function updateGetTreatmentNoNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetTreatmentNoNeedHPC
            Return MyBase.Channel.updateGetTreatmentNoNeedHPC(Card_Sn, retTreatmentValueList, retIllnessValueList)
        End Function
        
        Public Function deleteGetTreatmentNoNeedHPC(ByVal Card_Sn As String) As Integer Implements IccServiceReference.IIccService.deleteGetTreatmentNoNeedHPC
            Return MyBase.Channel.deleteGetTreatmentNoNeedHPC(Card_Sn)
        End Function
        
        Public Function insertGetTreatmentNoNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetTreatmentNoNeedHPC
            Return MyBase.Channel.insertGetTreatmentNoNeedHPC(Card_Sn, retTreatmentValueList, retIllnessValueList)
        End Function
        
        Public Function queryGetTreatmentNeedHPC(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetTreatmentNeedHPC
            Return MyBase.Channel.queryGetTreatmentNeedHPC(Card_Sn)
        End Function
        
        Public Function updateGetTreatmentNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetTreatmentNeedHPC
            Return MyBase.Channel.updateGetTreatmentNeedHPC(Card_Sn, retTreatmentValueList, retIllnessValueList)
        End Function
        
        Public Function deleteGetTreatmentNeedHPC(ByVal Card_Sn As String) As Integer Implements IccServiceReference.IIccService.deleteGetTreatmentNeedHPC
            Return MyBase.Channel.deleteGetTreatmentNeedHPC(Card_Sn)
        End Function
        
        Public Function insertGetTreatmentNeedHPC(ByVal Card_Sn As String, ByVal retTreatmentValueList As System.Data.DataSet, ByVal retIllnessValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetTreatmentNeedHPC
            Return MyBase.Channel.insertGetTreatmentNeedHPC(Card_Sn, retTreatmentValueList, retIllnessValueList)
        End Function
        
        Public Function queryGetRegisterPrevent(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetRegisterPrevent
            Return MyBase.Channel.queryGetRegisterPrevent(Card_Sn)
        End Function
        
        Public Function updateGetRegisterPrevent(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetRegisterPrevent
            Return MyBase.Channel.updateGetRegisterPrevent(Card_Sn, retValueList)
        End Function
        
        Public Function insertGetRegisterPrevent(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetRegisterPrevent
            Return MyBase.Channel.insertGetRegisterPrevent(Card_Sn, retValueList)
        End Function
        
        Public Function queryGetRegisterPregnant(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetRegisterPregnant
            Return MyBase.Channel.queryGetRegisterPregnant(Card_Sn)
        End Function
        
        Public Function updateGetRegisterPregnant(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetRegisterPregnant
            Return MyBase.Channel.updateGetRegisterPregnant(Card_Sn, retValueList)
        End Function
        
        Public Function insertGetRegisterPregnant(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetRegisterPregnant
            Return MyBase.Channel.insertGetRegisterPregnant(Card_Sn, retValueList)
        End Function
        
        Public Function queryReadPrescriptMain(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryReadPrescriptMain
            Return MyBase.Channel.queryReadPrescriptMain(Card_Sn)
        End Function
        
        Public Function updateReadPrescriptMain(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateReadPrescriptMain
            Return MyBase.Channel.updateReadPrescriptMain(Card_Sn, retValueList)
        End Function
        
        Public Function insertReadPrescriptMain(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertReadPrescriptMain
            Return MyBase.Channel.insertReadPrescriptMain(Card_Sn, retValueList)
        End Function
        
        Public Function queryReadPrescriptLongTerm(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryReadPrescriptLongTerm
            Return MyBase.Channel.queryReadPrescriptLongTerm(Card_Sn)
        End Function
        
        Public Function updateReadPrescriptLongTerm(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateReadPrescriptLongTerm
            Return MyBase.Channel.updateReadPrescriptLongTerm(Card_Sn, retValueList)
        End Function
        
        Public Function insertReadPrescriptLongTerm(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertReadPrescriptLongTerm
            Return MyBase.Channel.insertReadPrescriptLongTerm(Card_Sn, retValueList)
        End Function
        
        Public Function queryReadPrescriptHVE(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryReadPrescriptHVE
            Return MyBase.Channel.queryReadPrescriptHVE(Card_Sn)
        End Function
        
        Public Function updateReadPrescriptHVE(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateReadPrescriptHVE
            Return MyBase.Channel.updateReadPrescriptHVE(Card_Sn, retValueList)
        End Function
        
        Public Function insertReadPrescriptHVE(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertReadPrescriptHVE
            Return MyBase.Channel.insertReadPrescriptHVE(Card_Sn, retValueList)
        End Function
        
        Public Function queryReadPrescriptAllergic(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryReadPrescriptAllergic
            Return MyBase.Channel.queryReadPrescriptAllergic(Card_Sn)
        End Function
        
        Public Function updateReadPrescriptAllergic(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateReadPrescriptAllergic
            Return MyBase.Channel.updateReadPrescriptAllergic(Card_Sn, retValueList)
        End Function
        
        Public Function insertReadPrescriptAllergic(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertReadPrescriptAllergic
            Return MyBase.Channel.insertReadPrescriptAllergic(Card_Sn, retValueList)
        End Function
        
        Public Function queryGetInoculateData(ByVal Card_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetInoculateData
            Return MyBase.Channel.queryGetInoculateData(Card_Sn)
        End Function
        
        Public Function updateGetInoculateData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.updateGetInoculateData
            Return MyBase.Channel.updateGetInoculateData(Card_Sn, retValueList)
        End Function
        
        Public Function insertGetInoculateData(ByVal Card_Sn As String, ByVal retValueList As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.insertGetInoculateData
            Return MyBase.Channel.insertGetInoculateData(Card_Sn, retValueList)
        End Function
        
        Public Function insertInsertHealth(ByVal seqNumber As String, ByVal uploadType As String, ByVal sourceType1 As String, ByVal srcSeq As String, ByVal medicalRecNo As String, ByVal mb1Value As System.Data.DataSet, ByVal mb2ValueList As System.Data.DataSet, ByVal createUser As String, ByVal createTime As Date, ByVal errorCodeMessage As String) As Integer Implements IccServiceReference.IIccService.insertInsertHealth
            Return MyBase.Channel.insertInsertHealth(seqNumber, uploadType, sourceType1, srcSeq, medicalRecNo, mb1Value, mb2ValueList, createUser, createTime, errorCodeMessage)
        End Function
        
        Public Function insertInsertInoculate(ByVal seqNumber As String, ByVal uploadType As String, ByVal sourceType1 As String, ByVal srcSeq As String, ByVal medicalRecNo As String, ByVal fBabyStool As Boolean, ByVal mb1Value As System.Data.DataSet, ByVal mb2ValueList As System.Data.DataSet, ByVal createUser As String, ByVal createTime As Date, ByVal treatmentTime As Date) As Integer Implements IccServiceReference.IIccService.insertInsertInoculate
            Return MyBase.Channel.insertInsertInoculate(seqNumber, uploadType, sourceType1, srcSeq, medicalRecNo, fBabyStool, mb1Value, mb2ValueList, createUser, createTime, treatmentTime)
        End Function
        
        Public Function queryGetMustUploadField(ByVal treatmentCategoryId As String, ByVal dataType As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryGetMustUploadField
            Return MyBase.Channel.queryGetMustUploadField(treatmentCategoryId, dataType)
        End Function
        
        Public Function queryUpload(ByVal healthSnListStr As String, ByVal inoculationSnListStr As String, ByVal uploadTypeId As String, ByVal fBatch As Boolean, ByVal user As String, ByVal Config_Name_Path As String, ByVal Config_Name_Mail As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryUpload
            Return MyBase.Channel.queryUpload(healthSnListStr, inoculationSnListStr, uploadTypeId, fBatch, user, Config_Name_Path, Config_Name_Mail)
        End Function
        
        Public Function updateUpload(ByVal ds As System.Data.DataSet, ByVal user As String) As Integer Implements IccServiceReference.IIccService.updateUpload
            Return MyBase.Channel.updateUpload(ds, user)
        End Function
        
        Public Function updateUpload2(ByVal ds As System.Data.DataSet, ByVal UPLOAD_DATE As String, ByVal user As String) As Integer Implements IccServiceReference.IIccService.updateUpload2
            Return MyBase.Channel.updateUpload2(ds, UPLOAD_DATE, user)
        End Function
        
        Public Function queryMust_Field_Verify(ByVal mb1ValueA01 As String, ByVal mb1ValueA23 As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryMust_Field_Verify
            Return MyBase.Channel.queryMust_Field_Verify(mb1ValueA01, mb1ValueA23)
        End Function
        
        Public Function queryField_Length_Verify(ByVal totalID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryField_Length_Verify
            Return MyBase.Channel.queryField_Length_Verify(totalID)
        End Function
        
        Public Function querySelf_Verify(ByVal totalID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.querySelf_Verify
            Return MyBase.Channel.querySelf_Verify(totalID)
        End Function
        
        Public Function queryInteract_Verify1() As System.Data.DataSet Implements IccServiceReference.IIccService.queryInteract_Verify1
            Return MyBase.Channel.queryInteract_Verify1
        End Function
        
        Public Function queryInteract_Verify2() As System.Data.DataSet Implements IccServiceReference.IIccService.queryInteract_Verify2
            Return MyBase.Channel.queryInteract_Verify2
        End Function
        
        Public Function queryInteract_Verify3() As System.Data.DataSet Implements IccServiceReference.IIccService.queryInteract_Verify3
            Return MyBase.Channel.queryInteract_Verify3
        End Function
        
        Public Function queryInteract_Verify4() As System.Data.DataSet Implements IccServiceReference.IIccService.queryInteract_Verify4
            Return MyBase.Channel.queryInteract_Verify4
        End Function
        
        Public Function queryOnlineCheck(ByVal ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.queryOnlineCheck
            Return MyBase.Channel.queryOnlineCheck(ID)
        End Function
        
        Public Function ICCCloudDrugPatientQueryCountByChartNo(ByVal chartNo As String) As Integer Implements IccServiceReference.IIccService.ICCCloudDrugPatientQueryCountByChartNo
            Return MyBase.Channel.ICCCloudDrugPatientQueryCountByChartNo(chartNo)
        End Function
        
        Public Function ICCCloudDrugPatientQueryEffectivePatient() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCCloudDrugPatientQueryEffectivePatient
            Return MyBase.Channel.ICCCloudDrugPatientQueryEffectivePatient
        End Function
        
        Public Function ICCCloudDrugsQueryAssignColumnsByIdNo(ByVal idNo As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCCloudDrugsQueryAssignColumnsByIdNo
            Return MyBase.Channel.ICCCloudDrugsQueryAssignColumnsByIdNo(idNo)
        End Function
        
        Public Function ICCMustFieldVerifydeleteByPk(ByVal pkCode As String) As Integer Implements IccServiceReference.IIccService.ICCMustFieldVerifydeleteByPk
            Return MyBase.Channel.ICCMustFieldVerifydeleteByPk(pkCode)
        End Function
        
        Public Function ICCMustFieldVerifyinsert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCMustFieldVerifyinsert
            Return MyBase.Channel.ICCMustFieldVerifyinsert(ds)
        End Function
        
        Public Function ICCMustFieldVerifyupdate(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCMustFieldVerifyupdate
            Return MyBase.Channel.ICCMustFieldVerifyupdate(ds)
        End Function
        
        Public Function ICCMustFieldVerifyqueryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCMustFieldVerifyqueryAll
            Return MyBase.Channel.ICCMustFieldVerifyqueryAll
        End Function
        
        Public Function ICCMustFieldVerifyqueryByPK(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCMustFieldVerifyqueryByPK
            Return MyBase.Channel.ICCMustFieldVerifyqueryByPK(pk_Serial_Sn)
        End Function
        
        Public Function ICCMustFieldVerifyqueryByPKYNShow(ByRef pk_Serial_Sn As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCMustFieldVerifyqueryByPKYNShow
            Return MyBase.Channel.ICCMustFieldVerifyqueryByPKYNShow(pk_Serial_Sn)
        End Function
        
        Public Function ICCMustFieldVerifyqueryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCMustFieldVerifyqueryAllYNShow
            Return MyBase.Channel.ICCMustFieldVerifyqueryAllYNShow
        End Function
        
        Public Function ICCFieldLengthVerifydelete(ByVal pkCode As String) As Integer Implements IccServiceReference.IIccService.ICCFieldLengthVerifydelete
            Return MyBase.Channel.ICCFieldLengthVerifydelete(pkCode)
        End Function
        
        Public Function ICCFieldLengthVerifyqueryByPK(ByRef pk_ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCFieldLengthVerifyqueryByPK
            Return MyBase.Channel.ICCFieldLengthVerifyqueryByPK(pk_ID)
        End Function
        
        Public Function ICCFieldLengthVerifyinsert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCFieldLengthVerifyinsert
            Return MyBase.Channel.ICCFieldLengthVerifyinsert(ds)
        End Function
        
        Public Function ICCFieldLengthVerifyupdate(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCFieldLengthVerifyupdate
            Return MyBase.Channel.ICCFieldLengthVerifyupdate(ds)
        End Function
        
        Public Function ICCFieldLengthVerifyqueryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCFieldLengthVerifyqueryAll
            Return MyBase.Channel.ICCFieldLengthVerifyqueryAll
        End Function
        
        Public Function ICCOnlineCheckdelete(ByVal pk_ID As String) As Integer Implements IccServiceReference.IIccService.ICCOnlineCheckdelete
            Return MyBase.Channel.ICCOnlineCheckdelete(pk_ID)
        End Function
        
        Public Function ICCOnlineCheckqueryByPK(ByRef pk_ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCOnlineCheckqueryByPK
            Return MyBase.Channel.ICCOnlineCheckqueryByPK(pk_ID)
        End Function
        
        Public Function ICCOnlineCheckqueryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCOnlineCheckqueryAllYNShow
            Return MyBase.Channel.ICCOnlineCheckqueryAllYNShow
        End Function
        
        Public Function ICCOnlineCheckqueryByPKYNShow(ByRef pk_ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCOnlineCheckqueryByPKYNShow
            Return MyBase.Channel.ICCOnlineCheckqueryByPKYNShow(pk_ID)
        End Function
        
        Public Function ICCOnlineCheckinsert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCOnlineCheckinsert
            Return MyBase.Channel.ICCOnlineCheckinsert(ds)
        End Function
        
        Public Function ICCOnlineCheckupdate(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCOnlineCheckupdate
            Return MyBase.Channel.ICCOnlineCheckupdate(ds)
        End Function
        
        Public Function ICCOnlineCheckqueryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCOnlineCheckqueryAll
            Return MyBase.Channel.ICCOnlineCheckqueryAll
        End Function
        
        Public Function ICCSelfVerifydelete(ByVal pk_ID As String) As Integer Implements IccServiceReference.IIccService.ICCSelfVerifydelete
            Return MyBase.Channel.ICCSelfVerifydelete(pk_ID)
        End Function
        
        Public Function ICCSelfVerifyqueryByPK(ByRef pk_ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCSelfVerifyqueryByPK
            Return MyBase.Channel.ICCSelfVerifyqueryByPK(pk_ID)
        End Function
        
        Public Function ICCSelfVerifyqueryAllYNShow() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCSelfVerifyqueryAllYNShow
            Return MyBase.Channel.ICCSelfVerifyqueryAllYNShow
        End Function
        
        Public Function ICCSelfVerifyqueryByPKYNShow(ByRef pk_ID As String) As System.Data.DataSet Implements IccServiceReference.IIccService.ICCSelfVerifyqueryByPKYNShow
            Return MyBase.Channel.ICCSelfVerifyqueryByPKYNShow(pk_ID)
        End Function
        
        Public Function ICCSelfVerifyinsert(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCSelfVerifyinsert
            Return MyBase.Channel.ICCSelfVerifyinsert(ds)
        End Function
        
        Public Function ICCSelfVerifyupdate(ByVal ds As System.Data.DataSet) As Integer Implements IccServiceReference.IIccService.ICCSelfVerifyupdate
            Return MyBase.Channel.ICCSelfVerifyupdate(ds)
        End Function
        
        Public Function ICCSelfVerifyqueryAll() As System.Data.DataSet Implements IccServiceReference.IIccService.ICCSelfVerifyqueryAll
            Return MyBase.Channel.ICCSelfVerifyqueryAll
        End Function
        
        Public Function ICCInteractVerify1delete(ByRef pk_Serial_Sn As String) As Integer Implements IccServiceReference.IIccService.ICCInteractVerify1delete
            Return MyBase.Channel.ICCInteractVerify1delete(pk_Serial_Sn)
        End Function
    End Class
End Namespace
