'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CmmServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CmmServiceReference.ICmmService")>  _
    Public Interface ICmmService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/getPrinterName", ReplyAction:="http://tempuri.org/ICmmService/getPrinterNameResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Integer())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function getPrinterName(ByVal id As String, ByVal type As Integer, ByVal con As Object) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/getReportID", ReplyAction:="http://tempuri.org/ICmmService/getReportIDResponse")>  _
        Function getReportID() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodeBSSysCodeQuery", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodeBSSysCodeQueryResponse")>  _
        Function CMMSysCodeBSSysCodeQuery(ByVal CodeType As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodeBSSysCodeQueryMuti", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodeBSSysCodeQueryMutiResponse")>  _
        Function CMMSysCodeBSSysCodeQueryMuti(ByVal CodeType() As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodeTypeBSSysCodeTypeQuery", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodeTypeBSSysCodeTypeQueryResponse")>  _
        Function CMMSysCodeTypeBSSysCodeTypeQuery(ByVal TypeId As String, ByVal SystemName As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodequerySectionCode", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodequerySectionCodeResponse")>  _
        Function CMMSysCodequerySectionCode() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodequeryDeptTCodeBySectionCode", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodequeryDeptTCodeBySectionCodeResponse")>  _
        Function CMMSysCodequeryDeptTCodeBySectionCode() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICmmService/CMMSysCodeQueryPubConfigMuti", ReplyAction:="http://tempuri.org/ICmmService/CMMSysCodeQueryPubConfigMutiResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Integer())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String()))>  _
        Function CMMSysCodeQueryPubConfigMuti(ByVal configName() As String, ByRef conn As Object) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICmmServiceChannel
        Inherits CmmServiceReference.ICmmService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CmmServiceClient
        Inherits System.ServiceModel.ClientBase(Of CmmServiceReference.ICmmService)
        Implements CmmServiceReference.ICmmService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getPrinterName(ByVal id As String, ByVal type As Integer, ByVal con As Object) As String Implements CmmServiceReference.ICmmService.getPrinterName
            Return MyBase.Channel.getPrinterName(id, type, con)
        End Function
        
        Public Function getReportID() As String Implements CmmServiceReference.ICmmService.getReportID
            Return MyBase.Channel.getReportID
        End Function
        
        Public Function CMMSysCodeBSSysCodeQuery(ByVal CodeType As Integer) As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodeBSSysCodeQuery
            Return MyBase.Channel.CMMSysCodeBSSysCodeQuery(CodeType)
        End Function
        
        Public Function CMMSysCodeBSSysCodeQueryMuti(ByVal CodeType() As Integer) As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodeBSSysCodeQueryMuti
            Return MyBase.Channel.CMMSysCodeBSSysCodeQueryMuti(CodeType)
        End Function
        
        Public Function CMMSysCodeTypeBSSysCodeTypeQuery(ByVal TypeId As String, ByVal SystemName As String) As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodeTypeBSSysCodeTypeQuery
            Return MyBase.Channel.CMMSysCodeTypeBSSysCodeTypeQuery(TypeId, SystemName)
        End Function
        
        Public Function CMMSysCodequerySectionCode() As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodequerySectionCode
            Return MyBase.Channel.CMMSysCodequerySectionCode
        End Function
        
        Public Function CMMSysCodequeryDeptTCodeBySectionCode() As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodequeryDeptTCodeBySectionCode
            Return MyBase.Channel.CMMSysCodequeryDeptTCodeBySectionCode
        End Function
        
        Public Function CMMSysCodeQueryPubConfigMuti(ByVal configName() As String, ByRef conn As Object) As System.Data.DataSet Implements CmmServiceReference.ICmmService.CMMSysCodeQueryPubConfigMuti
            Return MyBase.Channel.CMMSysCodeQueryPubConfigMuti(configName, conn)
        End Function
    End Class
End Namespace
